### ISSUE TITLE
[FR] Support .strm files that use plugins

### ISSUE THREAD

**Issue by pank** [Zomboided/service.vpn.manager#10]
Hi,

First, thanks for your work on `service.vpn.manager`.  It works wonderfully!

In my library, I have a bunch of [`.strm` files](http://kodi.wiki/view/internet_video_and_audio_streams) that rely on a plugin.  E.g.:
```
$> cat $video-episode.strm
   plugin://plugin.video.myplugin/library/play/show/$T/season/$S/episode/$E
```

However, checking from the console OpenVPN is not triggered when such a stream is started from the library view rather than through the plugin itself.

I don't know if it is possible, but it would be pretty cool if such `.strm` would also consider the `service.vpn.manager` Add-on Filtering.

Thanks,
Rasmus

**Comment by Zomboided** [comment]
Assuming I could intercept the start of a stream, and then change the VPN after you've selected it (not sure that's possible without stopping it yet), how do you imagine the filtering would work?  I'm guessing you have 10s, if not 100s of .strm files.  Would you really want to identify which VPN you use for all of them?  Or do you imagine you'd have a default VPN for .strm files, and then define the deviations/exclusions?

**Comment by pank** [comment]
Hi,

In the example,

    plugin://plugin.video.myplugin/library/play/show/$T/season/$S/episode/$E

I use `myplugin`.  I had in mind that I’d already configured which VPN
profile `myplugin` should use via `service.vpn.manager`.  The difference
is that I now invoke `myplugin` implicitly from, say, the TV library
rather than through the addon menu.  I was hoping that the fact that I’m
still using `myplugin` would mean that it would be easy to pick the right
VPN.  But I don’t know the Kodi internals well enough to know if this is
true.

Alternatively, if it’s not possible to infer that a certain plugin is
invoked when using a strm file, it might be possible to do start it based
on a regexp matching against the path.

For example, I might say all strm files where the path match "BBC" should
use a VPN profile 1.  I don’t know how feasible that is, though.

Thanks,
Rasmus

**Comment by Zomboided** [comment]
Do you have an example of a *legal* stream I could add to my library to see what happens?

**Comment by pank** [comment]
Hi,

> Do you have an example of a *legal* stream I could add to my library to see what happens?

A general strm file?  Something like this:

    $> cat ~/videos/Badlands\ \(1973\)/badlands.strm
       https://archive.org/download/Badlands1973/Badlands%20(1973).mp4

For a plugin stream it would depend, I guess.  I use German Amazon Prime
Videos and I can "export" a show.  That creates a bunch of stream files.

     $> cd ~
     $> find . -iname "*preacher*"
        ./.kodi/userdata/addon_data/plugin.video.amazon-test/TV/Preacher
        ./.kodi/userdata/addon_data/plugin.video.amazon-test/TV/Preacher/Preacher - S01E01 - Pilot.strm
        ./.kodi/userdata/addon_data/plugin.video.amazon-test/TV/Preacher/Preacher - S01E01 - Pilot.nfo
        # ...
     $> cat ".kodi/userdata/addon_data/plugin.video.amazon-test/TV/Preacher/Preacher - S01E01 - Pilot.strm"
        plugin://plugin.video.amazon-test/?asin=B01G7JIFW2&mode=PlayVideo&adult=0&name=1+-+Pilot&trailer=0&selbitrate=0

I don’t know which plugins you have available, but I try to find a video
addon that has video integration and doesn’t require much effort to setup
if that’s helpful.

Thanks,
Rasmus

--

**Comment by Zomboided** [comment]
I added a player monitor to the code to see if I could detect the file that had been selected and I used the Badlands file.  If I create an .strm file, then I can detect it's started playing and output a message.  If I nobble that .strm file so that it can't be found, then nothing starts playing and I don't detect anything.

What I think this means is that if I were to need to switch VPNs, then I'd have to stop a stream that's already started (negating the point of a VPN to a degree), or the access of the stream would be rejected (maybe geolocked) and nothing would be started for me to recognise that I needed to change VPNs.

Unless there's a Kodi mechanism that I'm missing to intercept the player before it starts, then I don't think I can achieve what you need.

**Comment by pank** [comment]
Thanks for looking into it.  I don’t know where there’s hooks in Kodi.

Do you think it would be possible to trigger it based on the location of a
file?  I guess not, as the library view doesn’t really care about the
location...

**Comment by Zomboided** [comment]
No, I can find everything I need to about the file, and likely do some sort of filtering once the user has chosen to play a file.  The issue is that I can't intercept/block the play, connect the VPN, and then return to playing the file.  I can only do things after the play has started.

The advice I found on forums was basically this was the case, and that to do something differently you needed to put a call into the plugin (or native Kodi in this case).
