### ISSUE TITLE
Block internet access when VPN disconnects

### ISSUE THREAD

**Issue by PiE81** [Zomboided/service.vpn.manager#111]
Hi,
is it possible to block access to internet when no active VPN connection is available (or when vpn suddenly disconnect)?
Is it enough to activate "Stop streaming media when changing VPN"?

Thanks

**Comment by Zomboided** [comment]
No - if you really want to do this then you need to change the iptable.  You can do this using the up/down scripts https://github.com/Zomboided/service.vpn.manager/wiki/07.-Debug-Options#enable-updown-scripts and tailor the changes to your environment, or you can do this outside of the addon to deal with situations before the addon starts.

Personally, I want to be able to access the internet without a VPN (ie when accessing local geo resources that actively block VPNs).  That's why there are filters built into this addon to switch VPNs or turn it off.

The option you mention is designed to stop streaming when the VPN goes away unexpectedly.  If there are addons you only want to use with a VPN, there's filtering which will ensure the right VPN is turned on when you use the addon.

**Comment by PiE81** [comment]
Ok thanks.
I set  up a kill switch up.sh script using iptables commands.
It seems work and when the vpn disconnects, outside internet connections are blocked.
So I suppose that I can deactivate "Stop streaming media when changing VPN", is it right?

**Comment by Zomboided** [comment]
Yeah, the option you mention will just do a stop on the stream if it
detects the VPN has changed.  iptables will have blocked it well before
then and the stream should stop on its own.

Would you mind sharing your iptables up script here please?  I'd like to
see what you've done

**Comment by PiE81** [comment]
Yes, sure.. and thanks for eventual suggestions.

```
#!/bin/bash
iptables -F

iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -s 255.255.255.255/32 -j ACCEPT
iptables -A INPUT -s 192.168.0.0/16 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 1912 -j ACCEPT
iptables -A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT

iptables -A OUTPUT -o lo -j ACCEPT
iptables -A OUTPUT -d 255.255.255.255/32 -j ACCEPT
iptables -A OUTPUT -s 192.168.0.0/16 -j ACCEPT

iptables -A OUTPUT -p udp -m udp --dport 1912 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 1912 -j ACCEPT

iptables -A OUTPUT -o tun0 -j ACCEPT

iptables -P OUTPUT DROP
iptables -P INPUT DROP
iptables -P FORWARD DROP

ip6tables -P OUTPUT DROP
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
```
