### ISSUE TITLE
VPN Manager does not work if you move the Kodi User Data

### ISSUE THREAD

**Issue by BrooBee** [Zomboided/service.vpn.manager#12]
Hi,

Thanks a lot for this awesome Service :)

I have installed a fresh Kodi and then the service.vpn.manager and it works like a charm.

When I use -p to move the User Data to same folder where I installed Kodi the VPN stops working :(

Somehow the compiling of the Libs make the path go to:

C:\Users\NAME\Appdata\Roaming\Kodi\addons\service.vpn.manager\libs\ etc...

Instead of where I want the path to be, into the portable_data folder of my Installation of Kodi.

Is it possible to do anything about this?

Thanks again for this awesome work you done :)

Best Regards,

BrooBee

**Comment by Zomboided** [comment]
The code uses the Kodi special protocol denomination so that it works on all platforms.  - so the path you mention looks something like special://home/addons/service.vpn.manager, etc in the code.  If you mess with the location of it, then I'd suggest Kodi is not reporting the right directories to the plugin.  Either way, I'm not going to change this as it would break other platforms.
