### ISSUE TITLE
NordVPN as User Defined

### ISSUE THREAD

**Issue by platonx** [Zomboided/service.vpn.manager#120]
Hello,

how can I still configure NordVPN as User Defined in the VPNManager?

I have it out under User Defined with my NordVPN access data but it did not work out.

Can you help me please?

Thank you very much

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki/09.-User-Defined-VPNs

**Comment by nsheehan** [comment]
There needs to be more information in the article. I spent 2-3 hours trying to get this to work due to the missing information. Thanks to the openelec.tv forum I found this:
Alright, I got it to work with the following steps:

1. In VPN Manager go to Settings -> Utilities and select 'Reset all VPN provider files to default', then select 'Remove all downloaded VPN provider files'
2. Open a shell to your kodi, then download the server files from nordvpn from this source 'downloads.nordcdn.com/configs/archives/servers/ovpn.zip' using 'wget'
3. Unzip the file: 'unzip ovpn.zip'
4. download the nordvpn App on any pc.
5. Use it to connect to a server.
6. Wait for it to resolve your new IP. Write that down or leave it open.
7. Back in your downloaded server files go into the folder ovpn_udp.
8. Find the config file containing that IP you found via the command "grep -rn . -e 'ip-address'"
9. you should only find one file beginning with a country code and a number. remember that.
10. inside the folder ovpn_tcp, there should also be a file with the same country code and number
11. copy both files to /storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/
(you may have to create the folder 'UserDefined')
12. go to vpn manager settings and VPN configuration.
13. Select 'User Defined' as VPN Provider
14. Enter your username and password. (I already had that entered from before)
15. Further down in section 'advanced settings', go to Protocol filter and select 'UDP and TCP'
16. Now go to VPN Connections and click the first entry. It should now prompt you for your password and connect to the server.

These steps do work the "tip" was adding just a few NordVPN .ovpn files to the UserDefined folder or the 'VPN Manager for OpenVPN' chokes and hangs. Canceling doesn't work, you must reboot the device.
NordVPN was supported for over a year, I like many use Nord so why did you opt to drop support? Doesn't seem like a good choice.

**Comment by Zomboided** [comment]
Getting the files varies by provider, I'm not going to get into talking to how you obtain the files from every VPN provider - this isn't achievable (or something I want to do).

The rest of the steps look fine, but the import wizard will do all this for you. People are doing this for Nord successfully.

As far as dropping support, Nord keep changing their servers. I'm not wanting to spend any more of my time keeping them up to date when I don't have this to do with any of the other providers. Nord's infrastructure is not aligned with the way this addon works (or anyone that uses openvpn natively) and I'm not incentivised to support their users for free. The other option is to use their apps and avoid this problem but then you don't get the rest of the functionality of the addon, which might be fine for you

**Comment by platonx** [comment]
OK...thank you....but can I use the version 4.19 and deactivate the automatic update?

So I have with version 4.19 the NordVPN support.

Thank you

**Comment by Zomboided** [comment]
Yeah, this will work until Nord move their servers around again and it stops working - and then you'll left choosing between user defined and their app again
