### ISSUE TITLE
pidof errors in OSMC, cannot connect to VPN

### ISSUE THREAD

**Issue by lowkeyluce** [Zomboided/service.vpn.manager#148]
Hi,

I recently updated my installation of OSMC to the latest release (built on Stretch). Since then I'm unable to use VPN Manager. When I go to set up my primary VPN connection, I get the following error:

"The 'pdiof' command isn't writing out a response. Try changing the Kodi log directory setting in Settings-Debug menu and retry."

I've tried changing the logging settings but nothing helps. Kodi.log shows the following (full log file also attached):

16:46:38.087 T:1289745152    NONE: VPN Mgr : Entered connect.py with parameter 1
16:46:38.105 T:1289745152    NONE: VPN Mgr : Running connectVPN, connection_order is 1, profile is
16:46:38.105 T:1289745152   DEBUG: DialogProgress::Open called
16:46:38.105 T:1289745152   DEBUG: ------ Window Init (DialogConfirm.xml) ------
16:46:38.105 T:1289745152    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
16:46:38.134 T:1289745152    NONE: VPN Mgr : Connecting to first VPN
16:46:38.415 T:1391457024   ERROR: EXCEPTION: XBMC is not playing any file
16:46:38.650 T:1289745152    NONE: VPN Mgr : Checking openvpn (and maybe pidof and killall) can be run
16:46:38.675 T:1289745152    NONE: VPN Mgr : (Linux) Stopping VPN with sudo killall -9 openvpn
16:46:38.763 T:1289745152  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /home/osmc/.kodi/temp/openvpn.log &
16:46:39.206 T:1616474880    NONE: VPN Mgr : VPN monitor service was requested to run an update
16:46:39.218 T:1616474880    NONE: VPN Mgr : Update primary VPNs from settings
16:46:39.270 T:1616474880    NONE: VPN Mgr : Found no VPNs, setup is invalid
16:46:39.276 T:1616474880    NONE: VPN Mgr : Flag lists have changed
16:46:39.417 T:1391457024   ERROR: EXCEPTION: XBMC is not playing any file
16:46:39.841 T:1289745152  NOTICE: VPN Mgr : (platform.py) Testing pidof with : sudo pidof kodi.bin /home/osmc/.kodi/temp/command_test.txt>&/home/osmc/.kodi/temp/command_test.txt &
16:46:40.418 T:1391457024   ERROR: EXCEPTION: XBMC is not playing any file
16:46:51.005 T:1289745152   ERROR: Previous line repeats 10 times.
16:46:51.005 T:1289745152   ERROR: VPN Mgr : (platform.py) Ran pidof command and the log didn't appear

Any idea how I can get VPN Manager working again on OSMC? 

Thanks in advance. 

[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/1957021/kodi.log)

**Comment by Zomboided** [comment]
Are you making the addon yourself or using some random build that someone else thought they'd throw together?

If it's the latter, I'm not interested. If it's the former, when did you make it?

**Comment by lowkeyluce** [comment]
I'm not sure what addon you're referring to. The only addon involved here is the VPN Manager addon. I'm simply trying to use the VPN Manager addon in OSMC, which is listed as supported on your Wiki page. 

I'm not using an OSMC build if that's what you're asking. I installed OSMC from scratch and installed everything on top of that myself. 

I just wiped VPN Manager from my system, re-downloaded the zip file and reinstalled today to make sure that I'm running the latest release (v4.9.1). I'm also running the latest OpenVPN release for this distro (v2.4.0). Everything on this system is up to date.

**Comment by Zomboided** [comment]
Right, I'm asking how you got the VPN Mgr build. I've not released 4.9.1 as I made a bunch of changes and while they're checked into GitHub, I never did a release.  At some point in the middle of all my changes, some Internet hero did and that release was very broken.  If you're using that, just stop trying to make it work.

If you're making you're own add-on from the code that exists there currently then you're using the same version I'm currently testing and given you're on OSMC and I've not gotten around to installing an OSMC environment yet, I'd be happy with some help to fix the issue you're seeing. I can even share an "official" 4.9.1 later when I'm at my computer that I know is a good level.

Or you can use one of the releases on GitHub or in my Kodi repo which do work with OSMC

**Comment by Zomboided** [comment]
Latest release is here.  If this works, then close this.
https://github.com/Zomboided/service.vpn.manager/releases/tag/4.9.2

**Comment by Zomboided** [comment]
Now at https://github.com/Zomboided/service.vpn.manager/releases/tag/4.9.3
I had to zap 4.9.2.  If this works for you, then please let me know and close this.

**Comment by lowkeyluce** [comment]
Same problem with 4.9.3, unfortunately. 

For reference, I'm downloading the zip file directly from your Github, moving that zip file to my Raspberry Pi and installing via that zip file. I'm not using any third party releases of VPN Manager.

**Comment by Zomboided** [comment]
Can you click default on the settings, the. Just switch on debug in the advanced tab, then reboot, then when it comes back use the wizard to set it up. If that fails save off the kodi log and share it with me

**Comment by Zomboided** [comment]
Here's something else to try before gathering a log.  You need a command line, so ssh onto the box and then issue the following command exactly as is - don't add any spaces, etc, don't truncate it

sudo pidof kodi.bin /home/osmc/.kodi/temp/command_test.txt>&/home/osmc/.kodi/temp/command_test.txt &

Let me know what the error message is as I'm not able to trace how this goes wrong (I Just know that it does).  If it does work, check out /home/osmc/,kodi/command_text.txt and tell me what you see.

**Comment by Zomboided** [comment]
I've just installed and run this on the latest OSMC RPi build and the pidof test works just fine.  I'm closing this.  If you're still having issues, reinstall time.

**Comment by Zomboided** [comment]
Spoke too soon, pidof was working fine, but killall was making the pidof test seem like it was failing.  Anyway, all fixed in 4.9.4

**Comment by WACKYF0X** [comment]
Hello Zomboided:
Same problem with kodi 17.6, and everything installed - openvpn (perfectly run in console), killall and pidof guess. But when i trying to install addon it gave me an error.
I install latest vpnmanager from your repo: " service.vpn.manager-5.0.7 "

> Here's something else to try before gathering a log. You need a command line, so ssh onto the box and then issue the following command exactly as is - don't add any spaces, etc, don't truncate it
> 
> sudo pidof kodi.bin/home/USER/.kodi/temp/command_test.txt>&
/home/USER/.kodi/temp/command_test.txt &
> 
> Let me know what the error message is as I'm not able to trace how this goes wrong (I Just know that it does). If it does work, check out /home/osmc/,kodi/command_text.txt and tell me what you see.

[1] 17087

**Comment by Zomboided** [comment]
Need to see a debug log

**Comment by WACKYF0X** [comment]
Here it is

сб, 24 нояб. 2018 г. в 12:41, Zomboided <notifications@github.com>:

> Need to see a debug log
>

**Comment by WACKYF0X** [comment]
> ﻿22:51:33.606 T:140320065739136  NOTICE: special://profile/ is mapped to: special://masterprofile/
22:51:33.606 T:140320065739136  NOTICE: -----------------------------------------------------------------------
22:51:33.606 T:140320065739136  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Linux x86 64-bit
22:51:33.606 T:140320065739136  NOTICE: Using Release Kodi x64 build
22:51:33.606 T:140320065739136  NOTICE: Kodi compiled Nov  4 2012 by GCC 5.4.0 for Linux x86 64-bit version 4.4.90 (263258)
22:51:33.606 T:140320065739136  NOTICE: Running on Linux Mint 18.3, kernel: Linux x86 64-bit version 4.13.0-39-generic
22:51:33.606 T:140320065739136  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
22:51:33.606 T:140320065739136  NOTICE: Host CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz, 4 cores available
22:51:33.606 T:140320065739136  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
22:51:33.606 T:140320065739136  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
22:51:33.606 T:140320065739136  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
22:51:33.606 T:140320065739136  NOTICE: special://masterprofile/ is mapped to: /home/redfox/.kodi/userdata
22:51:33.606 T:140320065739136  NOTICE: special://envhome/ is mapped to: /home/redfox
22:51:33.606 T:140320065739136  NOTICE: special://home/ is mapped to: /home/redfox/.kodi
22:51:33.606 T:140320065739136  NOTICE: special://temp/ is mapped to: /home/redfox/.kodi/temp
22:51:33.606 T:140320065739136  NOTICE: special://logpath/ is mapped to: /home/redfox/.kodi/temp
22:51:33.606 T:140320065739136  NOTICE: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin
22:51:33.606 T:140320065739136  NOTICE: Local hostname: Wubbalubbadubdub
22:51:33.606 T:140320065739136  NOTICE: Log File is located: /home/redfox/.kodi/temp//kodi.log
22:51:33.606 T:140320065739136  NOTICE: -----------------------------------------------------------------------
22:51:33.613 T:140320065739136   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanSuspend'
22:51:33.614 T:140320065739136   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanHibernate'
22:51:33.634 T:140320065739136   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'OnLowBattery'
22:51:33.634 T:140320065739136  NOTICE: load settings...
22:51:33.642 T:140320065739136  NOTICE: Found 1 Lists of Devices
22:51:33.642 T:140320065739136  NOTICE: Enumerated PULSE devices:
22:51:33.642 T:140320065739136  NOTICE:     Device 1
22:51:33.642 T:140320065739136  NOTICE:         m_deviceName      : Default
22:51:33.642 T:140320065739136  NOTICE:         m_displayName     : Default
22:51:33.642 T:140320065739136  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
22:51:33.642 T:140320065739136  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:51:33.642 T:140320065739136  NOTICE:         m_channels        : FL,FR
22:51:33.642 T:140320065739136  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
22:51:33.642 T:140320065739136  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
22:51:33.643 T:140320065739136  NOTICE:         m_streamTypes     : No passthrough capabilities
22:51:33.643 T:140320065739136  NOTICE:     Device 2
22:51:33.643 T:140320065739136  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_1f.3.analog-stereo
22:51:33.643 T:140320065739136  NOTICE:         m_displayName     : Built-in Audio Analog Stereo
22:51:33.643 T:140320065739136  NOTICE:         m_displayNameExtra: Headphones (PULSEAUDIO)
22:51:33.643 T:140320065739136  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:51:33.643 T:140320065739136  NOTICE:         m_channels        : FL,FR
22:51:33.643 T:140320065739136  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
22:51:33.643 T:140320065739136  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
22:51:33.643 T:140320065739136  NOTICE:         m_streamTypes     : No passthrough capabilities
22:51:33.644 T:140320065739136  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
22:51:33.644 T:140320065739136  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
22:51:33.644 T:140320065739136  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <useddsfanart>true</useddsfanart>
                                              <cputempcommand>cputemp</cputempcommand>
                                              <gputempcommand>gputemp</gputempcommand>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                              <network>
                                                <cachemembuffersize>234603008</cachemembuffersize>
                                                <readbufferfactor>2</readbufferfactor>
                                                <curlclienttimeout>45</curlclienttimeout>
                                                <disableipv6>true</disableipv6>
                                              </network>
                                            </advancedsettings>
22:51:33.644 T:140320065739136  NOTICE: Default Video Player: VideoPlayer
22:51:33.644 T:140320065739136  NOTICE: Default Audio Player: paplayer
22:51:33.644 T:140320065739136  NOTICE: Disabled debug logging due to GUI setting. Level 0.
22:51:33.644 T:140320065739136  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
22:51:33.644 T:140320065739136  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
22:51:33.644 T:140320065739136  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
22:51:33.644 T:140320065739136  NOTICE: Loaded playercorefactory configuration
22:51:33.644 T:140320065739136  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
22:51:33.644 T:140320065739136  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
22:51:33.646 T:140320065739136  NOTICE: Running database version Addons27
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.xbmc.org
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.Fishenzon
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.kodil
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.xbmc-israel
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.movix
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.sdarot
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.gaia.3
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.gaia.2
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.gaia.1
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.exodusredux
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.no-issue
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.tva.common
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.xbmchub
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository superrepo.kodi.krypton.hebrew
22:51:35.485 T:140320065739136  NOTICE: ADDONS: Using repository repository.zomboided.plugins
22:51:35.499 T:140319467239168  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
22:51:35.653 T:140320065739136  NOTICE: Checking resolution 16
22:51:35.689 T:140320065739136 WARNING: CWinEventsX11::Init - no input method found
22:51:35.718 T:140320065739136  NOTICE: Using visual 0x20
22:51:35.726 T:140320065739136  NOTICE: GL_VENDOR = Intel Open Source Technology Center
22:51:35.726 T:140320065739136  NOTICE: GL_RENDERER = Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)
22:51:35.726 T:140320065739136  NOTICE: GL_VERSION = 3.0 Mesa 18.0.5
22:51:35.726 T:140320065739136  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.30
22:51:35.726 T:140320065739136  NOTICE: GL_EXTENSIONS = GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_gpu_program_parameters GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays
22:51:35.840 T:140319558334208  NOTICE: Running database version Addons27
22:51:35.841 T:140319558334208  NOTICE: Running database version ViewModes6
22:51:35.841 T:140319558334208  NOTICE: Running database version Textures13
22:51:35.842 T:140319558334208  NOTICE: Running database version MyMusic60
22:51:35.843 T:140319558334208  NOTICE: Running database version MyVideos107
22:51:35.844 T:140319558334208  NOTICE: Running database version TV29
22:51:35.845 T:140319558334208  NOTICE: Running database version Epg11
22:51:35.847 T:140320065739136  NOTICE: start dvd mediatype detection
22:51:35.913 T:140320065739136 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
22:51:35.960 T:140320065739136  NOTICE: initialize done
22:51:35.960 T:140320065739136  NOTICE: Running the application...
22:51:35.962 T:140320065739136  NOTICE: starting zeroconf publishing
22:51:35.962 T:140320065739136  NOTICE: starting upnp client
22:51:35.974 T:140317579798272  NOTICE: ES: Starting UDP Event server on port 9777
22:51:35.974 T:140317579798272  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
22:51:36.294 T:140318476482304  NOTICE: [Exodus Redux] ######################### EXODUS REDUX ############################
22:51:36.294 T:140318476482304  NOTICE: [Exodus Redux] ####### CURRENT EXODUS REDUX VERSIONS REPORT ######################
22:51:36.294 T:140318476482304  NOTICE: [Exodus Redux] ### EXODUS REDUX PLUGIN VERSION: 1.0.7 ###
22:51:36.294 T:140318476482304  NOTICE: [Exodus Redux] ### EXODUS REDUX SCRIPT VERSION: 1.0.9 ###
22:51:36.294 T:140318476482304  NOTICE: [Exodus Redux] ###############################################################
22:52:04.409 T:140320065739136 WARNING: CWinEventsX11::Init - no input method found
22:52:50.726 T:140318057953024 WARNING: Previous line repeats 1 times.
22:52:50.726 T:140318057953024  NOTICE: VPN Mgr : (service.py) Starting VPN monitor service, platform is 2, version is 5.0.7
22:52:50.726 T:140318057953024  NOTICE: VPN Mgr : (service.py) Kodi build is 17.6 Git:20171114-a9a7a20
22:52:50.726 T:140318057953024  NOTICE: VPN Mgr : (service.py) Addon path is /home/redfox/.kodi/addons/service.vpn.manager/
22:52:53.986 T:140318057953024  NOTICE: VPN Mgr : (platform.py) Testing openvpn with : sudo /usr/sbin/openvpn > /home/redfox/.kodi/temp/openvpn.log 2>&1 &
22:52:54.998 T:140318057953024   ERROR: VPN Mgr : (platform.py) Ran openvpn command and it failed
22:52:54.999 T:140318057953024  NOTICE: VPN Mgr : (platform.py) VPN log file start >>>
22:52:54.999 T:140318057953024  NOTICE: sudo: no tty present and no askpass program specified
22:52:54.999 T:140318057953024  NOTICE: VPN Mgr : (platform.py) <<< VPN log file end
22:52:59.316 T:140318057953024  NOTICE: VPN Mgr : (platform.py) Testing killall with : sudo killall vpnmanagertest > /home/redfox/.kodi/temp/command_test.txt 2>&1 &
22:53:00.333 T:140318057953024   ERROR: VPN Mgr : (platform.py) Ran killall command and it failed
22:53:00.334 T:140318057953024  NOTICE: VPN Mgr : (platform.py) Command test file start >>>
22:53:00.334 T:140318057953024  NOTICE: sudo: no tty present and no askpass program specified
22:53:00.334 T:140318057953024  NOTICE: VPN Mgr : (platform.py) <<< Command test file end

**Comment by WACKYF0X** [comment]
> Need to see a debug log

[https://drive.google.com/open?id=1KUpJd-AflTpzy0fjzaYVsvxr2XPs4kPE](url)

**Comment by Zomboided** [comment]
killall is failing.  I think you need to remove the requirement to enter a
password when running killall on OSMC

**Comment by Zomboided** [comment]
Actually, openvpn is failing too, so that needs to be able to run with sudo
without a password.  And pidof whilst you're at it.

**Comment by ChristianCook66** [comment]
i just updated to kodi 17.6 and am also experiencing this. Is there a way to bypass or a new vpn manager update coming?

**Comment by Zomboided** [comment]
To fix OSMC as detailed in this thread.  Or use LibreELEC.  VPN Mgr is not
going to set up your operating system for you....

**Comment by ChristianCook66** [comment]
im sorry i used the same app on kodi on a raspberry pi 3bplus and worked fine now i get the error killall and piof ne to be installed i updated and got the same message vpn manager installed perfect but the same pidof and killall error?

**Comment by Zomboided** [comment]
if pidof and killall can't be called, then VPN Mgr won't work.  I've told
you how to fix it.
