### ISSUE TITLE
Error connecting to vpn, something unexpected happened

### ISSUE THREAD

**Issue by PiGuy3** [Zomboided/service.vpn.manager#165]
Hello. Im new to the whole opensource world and I just started my raspberry pi adventures last week. I wanted to make my home-media player device with my pi and installed osmc. I realized that a vpn would be needed so i tried downloading the vpn manager for openvpn. After figuring out how to get the killall dependancy i thought i got this thing figured out but as my device is connecting to the vpn it gives me this strange error saying something unexpected happened. Ive attached the log so hopefully someone can help me find a solution. Really excited to use this add on and i need help.

**Comment by Zomboided** [comment]
Post the debug log on Pastebin. That link looks random enough for me to not want to click on it

**Comment by PiGuy3** [comment]
Well i wake up the next morning to see if anything has improved to my benefit and im greeted with an error saying that authentication failed. I quadruple checked the passwords with my vpns website and login instruction. @zomboided for the debug logs do i just put the vpn error log?

**Comment by Zomboided** [comment]
If it says authentication failed rather than the first error you mentioned then it means that you're using the wrong credentials. The log will say just that - I'm not sure what more I'm gonna say to that. If you're still getting the other error, I'll look at it. Instructions for getting logs are on the trouble shooting page of the wiki
