### ISSUE TITLE
Manager not disconnecting

### ISSUE THREAD

**Issue by Sajk123** [Zomboided/service.vpn.manager#209]
I'm a new user to the manager in Windows 8.1. Since my VPN provider is not supported I have been able to import it manually in the service, and I managed to do that and connect to it. 
I was looking for a way to simply connect and disconnect from my VPN by mapping a button to the connection table and this also works, I choose the server and it connects, however if I want to disconnect I press the button, choose disconnect and it says that I'm disconnected, but I am not. When I tab out to windows and check the IP it still shows the VPNs IP-address.

I noticed that the only way for me to really disconnect from the VPN is to go into the taskmanager and end the "Open VPN deamon" task that is running.

Am I doing something wrong?

**Comment by Zomboided** [comment]
It connects and disconnects for me on Windows 7, I've never tried it on 8,
but it's fine on 10.
The way the code works is that it will kill the running task and wait for
it to go away.  If it doesn't go away, there will be an error in the log.
You should switch on the PID column in Task Manager and when you're
connected, see what the PID number is.  As you do the disconnect, and the
openvpn task doesn't go away, see if the PID number machines - if it
doesn't it means that something is restarting it.  Maybe you've got an
application from your VPN provider doing this, maybe it's something in the
openvpn file that's doing the restart.  You can read the openvpn parameters
to find this, I can't remember which param this is.

If you really think this is a problem, caused by the addon rather than your
provider files/environment then I'm happy to see a log.
So move to 5.0.7 - pick up the release from the repository or from Github.
Don't use the latest branch as I'm in the middle of adding support for a
new provider.
Then switch on debug in Settings/Advanced/Enable debug
The get a log of the connect/disconnect cycle and screen shots of Task
Manager wtih the PID switched on.

**Comment by Sajk123** [comment]
Thank you for taking the time to answer and also developing this wonderful addon, once its setup correctly it will save me alot of headaches.

I will get back with logs during this week.

**Comment by Sajk123** [comment]
Zomboided, sorry for the late response.

I managed to get the manager working on my other HTPC just way I needed it to, so the issue above has to be related to something else other than the manager. So this is solved now.

Thank you for your work!
