### ISSUE TITLE
NordVPN Authentication not possible

### ISSUE THREAD

**Issue by dillasyx** [Zomboided/service.vpn.manager#227]
So I just installed LibreELEC 9.0.1 and then installed this addon via zip, as the versioning in the repo is different.
My RasPi is connected to the internet and my password and username are 100% correct. I checked it more than 10 times.
So while running the Wizard and entering everything, I always get the authentication error.
I am using NordVPN. On Kodi 17 I used this addon too, but manually configured NordVPN and it worked.

**Comment by Zomboided** [comment]
Need to see a full log with debug

**Comment by dillasyx** [comment]
2019-03-01 18:31:53.611 T:1700045680  NOTICE: VPN Mgr : (service.py) Starting VPN monitor service, platform is 2, version is 6.0.2
2019-03-01 18:31:53.612 T:1700045680  NOTICE: VPN Mgr : (service.py) Kodi build is 18.1 Git:newclock5_18.1-Leia
2019-03-01 18:31:53.612 T:1700045680  NOTICE: VPN Mgr : (service.py) Addon path is /storage/.kodi/addons/service.vpn.manager/
2019-03-01 18:32:31.137 T:1700045680   ERROR: VPN Mgr : (alternativeNord.py) Couldn't authenticate with NordVPN
2019-03-01 18:32:31.137 T:1700045680   ERROR: VPN Mgr : (alternativeNord.py) API call was https://api.nordvpn.com/v1/users/tokens, username=censored&password=censored
2019-03-01 18:32:31.137 T:1700045680   ERROR: VPN Mgr : (alternativeNord.py) Response was 401 Unauthorized
2019-03-01 18:32:31.144 T:1700045680   ERROR: VPN Mgr : (alternativeNord.py) {"errors":{"code":101301,"message":"Unauthorized"}}
2019-03-01 18:32:32.708 T:1700045680   ERROR: VPN Mgr : (common.py) Could not authenticate with VPN provider. Please check user name and password and try again.
2019-03-01 18:33:26.082 T:1666474864  NOTICE: ES: Client  from ::ffff:192.168.178.70 timed out
2019-03-01 18:39:48.855 T:1629623152   ERROR: GetDirectory - Error getting
2019-03-01 18:40:21.921 T:1937698336   ERROR: Previous line repeats 2 times.
2019-03-01 18:40:21.922 T:1937698336  NOTICE: Log level changed to "LOG_LEVEL_DEBUG_FREEMEM"
2019-03-01 18:40:21.922 T:1937698336  NOTICE: Enabled debug logging due to GUI setting. Level 2.

**Comment by Zomboided** [comment]
That’s not a full debug log. The whole thing, not just the bits you think are relevant

**Comment by dillasyx** [comment]
Here is the full, had to check, if i have to censor some data, sorry.

[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/2922290/kodi.log)

**Comment by Zomboided** [comment]
You’ll need to switch debug on in settings/advanced in the addon settings menu. Using the general debug results in a log with just so much noise in it it’s totally unreadable, sorry

**Comment by Zomboided** [comment]
Don't bother just yet, I may have spotted the lines I needed to see

**Comment by Zomboided** [comment]
I've just tried this using my expired NordVPN account, with version 6.1.0, and a fresh install on Windows.  The call that you're saying is failing is working just fine for me.  I don't get an auth error until I actually try and do the connection.

I can't remember exactly how Nord structure their service.  The ID and password I enter is the same as the one I use to access my account on their website.  The addon fetches a user ID and password to use to attach to a VPN server.  It's not the same as the ID and password used to access the website.

So I suspect the fact you're seeing unauthorized is because you're not supplying the correct credentials.  This is what the Nord API that's being called is reporting.

**Comment by dillasyx** [comment]
Found the problem. It wasn't the username as it is the same as on the website, if you didn't contact the support to change it. It is the password as my has special characters in it and the API can't handle it. At least this is what the support told me. Just wanted to give that info, if someone else has this problem.

![support nordvpn](https://user-images.githubusercontent.com/11612223/53689140-1ffe9700-3d4f-11e9-93ef-c96915604a8d.jpg)

**Comment by Zomboided** [comment]
Ok thanks for mentioning this

**Comment by edjw** [comment]
If you have a special character in your username/email address, then it will fail as well. xx+xx@domain.tld will fail for example

**Comment by Blinchik91** [comment]
Same problem here, my password Does not contain any special character and it still doesn’t work... it worked once and now not

**Comment by Dliix66** [comment]
Same here, I removed all special characters from my password, still can't login...

**Comment by peno64** [comment]
Nordvpn is working fine here...
________________________________

**Comment by Zomboided** [comment]
Works for me too (as of 2 days ago)...although I can't connect the VPN because my account is expired.  If this isn't working for you, reset the VPN provider (Settings/Utilities I think) and try again to force a new authentication.  If this still doesn't work for you, then take it up with Nord.

**Comment by Blinchik91** [comment]
> Works for me too (as of 2 days ago)...although I can't connect the VPN because my account is expired. If this isn't working for you, reset the VPN provider (Settings/Utilities I think) and try again to force a new authentication. If this still doesn't work for you, then take it up with Nord.

Already talk to them, they told me to use the ovpn files to connect manually. This workaround works for me but it’s not very comfortable.

**Comment by Zomboided** [comment]
Then you'll need to get a log as described in the wiki on the Trouble Shooting page, with both debug, http and json debug switched on.

**Comment by peno64** [comment]
Edit /storage/.kodi/userdata/addon_data/service.vpn.manager/settings.xml with a text editor. There you will find your entered credentials and you can see if they are correct.
________________________________

**Comment by Zomboided** [comment]
Thanks @peno64, this is sort of right, but those credentials are then used
to go and "log on" to the API that Nord provide, which in turn provides
further credentials that are used to then establish a VPN.  So it's a
worthwhile checking this, but if it doesn't work, I'd still wanna see a
trace as mentioned.

**Comment by Blinchik91** [comment]
> 2020-09-11 10:21:12.597 T:2633094000    NONE: VPN Mgr : Requested update to service process via settings monitor
2020-09-11 10:21:12.619 T:2073469808 WARNING: CPythonInvoker(50): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
2020-09-11 10:21:12.775 T:2633094000    NONE: VPN Mgr : Update service requested KodiMonitor
2020-09-11 10:21:13.309 T:2633094000    NONE: VPN Mgr : VPN monitor service was requested to run an update
2020-09-11 10:21:13.360 T:2633094000    NONE: VPN Mgr : Update primary VPNs from settings
2020-09-11 10:21:13.403 T:2073469808    NONE: VPN Mgr : Entered connect.py with parameter 1
2020-09-11 10:21:13.437 T:2073469808    NONE: VPN Mgr : Running connectVPN, connection_order is 1, profile is
2020-09-11 10:21:13.458 T:2073469808    NONE: VPN Mgr : Connecting to first VPN
2020-09-11 10:21:13.515 T:2633094000    NONE: VPN Mgr : Found no VPNs, setup is invalid
2020-09-11 10:21:13.533 T:2633094000    NONE: VPN Mgr : Flag lists have changed
2020-09-11 10:21:14.010 T:2073469808    NONE: VPN Mgr : Requesting service stops
2020-09-11 10:21:18.589 T:2633094000    NONE: VPN Mgr : Service received a stop request
2020-09-11 10:21:19.036 T:2073469808    NONE: VPN Mgr : VPN monitor paused
2020-09-11 10:21:19.553 T:2073469808    NONE: VPN Mgr : Stopping VPN
2020-09-11 10:21:19.681 T:2073469808    NONE: VPN Mgr : (Linux) Stopping VPN with killall -15 openvpn
2020-09-11 10:21:21.997 T:2073469808    NONE: VPN Mgr : Credentials need to be validated
2020-09-11 10:21:22.458 T:2073469808  NOTICE: VPN Mgr : (alternativeNord.py) Authenticating with VPN using https://api.nordvpn.com/v1/users/tokens, username=***%40****.com&password=************
2020-09-11 10:21:23.543 T:2073469808   ERROR: VPN Mgr : (alternativeNord.py) Couldn't authenticate with NordVPN
2020-09-11 10:21:23.544 T:2073469808   ERROR: VPN Mgr : (alternativeNord.py) API call was https://api.nordvpn.com/v1/users/tokens, username=***%40****.com&password=************
2020-09-11 10:21:23.544 T:2073469808   ERROR: VPN Mgr : (alternativeNord.py) Response was <class 'ssl.SSLError'> ('The read operation timed out',)
2020-09-11 10:21:24.540 T:2073469808   ERROR: VPN Mgr : (common.py) Could not authenticate with VPN provider. Please check user name and password and try again.
2020-09-11 10:21:24.617 T:2073469808    NONE: VPN Mgr : (Linux) Stopping VPN with killall -9 openvpn
2020-09-11 10:21:24.651 T:2073469808    NONE: VPN Mgr : Requesting service restarts
2020-09-11 10:21:26.681 T:2633094000    NONE: VPN Mgr : Service received a start request
2020-09-11 10:21:34.130 T:2073469808    NONE: VPN Mgr : Exit connect.py
2020-09-11 10:21:43.101 T:2073469808 WARNING: CPythonInvoker(51): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.


Is that enough or do you need more ?

**Comment by Zomboided** [comment]
I suspect this is a network problem.  Can you ping api.nordvpn.com using
the command line?  Can you ping google.com?

**Comment by Blinchik91** [comment]
> I suspect this is a network problem. Can you ping api.nordvpn.com using the command line? Can you ping google.com?
> […](#)

Is pingable, nordvpnapi and google

**Comment by Zomboided** [comment]
Edit /storage/.kodi/addons/service.vpn.manager/libs/alternativeNord.py
Line 55 is: response = urllib2.urlopen(req)
Change it to: response = urllib2.urlopen(req**, timeout=10**)

**Comment by Blinchik91** [comment]
It seems to work! But as I said, I've had this case before and then suddenly it stopped working. I will watch it.

**Comment by Zomboided** [comment]
Probably but I'm not sure where it's set, so the Nord API calls will use a 10 second time out as of 6.3.6 which is live in the repo now.

**Comment by JuliusCaeser2030** [comment]
Hi all,

I had the same problems on Kodi getting Nord VPN to authenticate. I finally got it to work. I just can't remember every step about how I did it but I can give you some tips. You have to think outside the box. If you already using NordVPN on other devices such as PC etc...then write down the number of the servers available in each country (important).  For example, there are two in Germany. Berlin = #1089 and Frankfurt = #1036. Now go to https://nordvpn.com/de/ovpn/ and download the config files for the servers with these numbers. E.g I would look for de1036.nordvpn.com if I want to connect to Frankfurt. In my opinion, the rest don't work or authenticate. Just two will from many. That's the problem. NordVPN has a shitty list. Download UDP config files for this server. TCP may not work. Put this config file on a UST stick. Connect to a Raspberry Pie or whatever, then run the wizard or connect manually but this time make sure not to change settings as recommened. CHANGE NOTHING. Keep the config file for the exact server you want to connect to as is in the country that matches the real available updated server and it will work. It did for me anyway. The downside, is that NordVPN says...first server connection and then the rest will be updated. It again, doesn't do this. You just have one config. So you have to repeate the above to add some more and manually update them if they change or are unanavilable. I'd recommend have 2-3 in country, region plus one or two outside. THIS IS NOT A USERNAME / PASSWORD error. It is shit programming by NordVPN.

**Comment by peno64** [comment]
@JuliusCaeser2030 
Have you tried the updated addon with the new procedure? Works like a charm here.

**Comment by peno64** [comment]
@JuliusCaeser2030 

see https://github.com/Zomboided/service.vpn.manager/issues/395

It's pinned on top of the issues...

**Comment by JuliusCaeser2030** [comment]
I updated the add-on and installed the latest version of NordVPN on Kodi/Libreelec but I agree the tokens could be a valid solution. I got it to work anyway with some hacking but I will try your solution to see if the servers are updated regulary and available everywhere like on a Windows experience. Linux vs Windows will always be different- will respond soon because I need a better solution. It it works, NordVPN (great service) - needs to communicate this and update documentation. I know. We are Kodi users. Nobody wants to update thieves-

**Comment by JuliusCaeser2030** [comment]
That option didn't work. 

The NordVPN app 5.0.0. on LibreElec 9.2.8 (Linux Kernel 4.19.127). doesn't have the option to add or use tokens. I did generate one the way you said and have one but I can't use so I reconnected back to a server here that I verified works with normal account/password. For example, in Australia; I can see there are 5 servers but in this list https://nordvpn.com/de/ovpn/ there are 50+. Only 5 configs will work. Brisbane for example is using #734, so if you download the config and change nothing during setup you can connect to au734.nordvpn.com once you download the UDP config file for this server.

e.g. 
au529.nordvpn.com
au530.nordvpn.com
au531.nordvpn.com
au532.nordvpn.com
au533.nordvpn.com
au534.nordvpn.com
au535.nordvpn.com
au536.nordvpn.com
au537.nordvpn.com
au538.nordvpn.com
au569.nordvpn.com
au570.nordvpn.com
au576.nordvpn.com
au585.nordvpn.com
au586.nordvpn.com
au587.nordvpn.com
au588.nordvpn.com
au595.nordvpn.com
au596.nordvpn.com
au599.nordvpn.com
au600.nordvpn.com
au601.nordvpn.com
au602.nordvpn.com
au605.nordvpn.com
au606.nordvpn.com
au607.nordvpn.com
au610.nordvpn.com
au611.nordvpn.com
au612.nordvpn.com
au613.nordvpn.com
au614.nordvpn.com
au615.nordvpn.com
au623.nordvpn.com
au624.nordvpn.com
au638.nordvpn.com
au639.nordvpn.com
au640.nordvpn.com
au641.nordvpn.com
au642.nordvpn.com
au643.nordvpn.com
au644.nordvpn.com
au645.nordvpn.com
au646.nordvpn.com
au647.nordvpn.com
au648.nordvpn.com
au649.nordvpn.com
au650.nordvpn.com
au651.nordvpn.com
au652.nordvpn.com
au653.nordvpn.com
au654.nordvpn.com
au655.nordvpn.com
au656.nordvpn.com
au657.nordvpn.com
au658.nordvpn.com
au659.nordvpn.com
au660.nordvpn.com
au661.nordvpn.com
au662.nordvpn.com
au663.nordvpn.com
au665.nordvpn.com
au666.nordvpn.com
au667.nordvpn.com
au668.nordvpn.com
au669.nordvpn.com
au670.nordvpn.com
au671.nordvpn.com
au673.nordvpn.com
au680.nordvpn.com
au681.nordvpn.com
au682.nordvpn.com
au684.nordvpn.com
au685.nordvpn.com
au686.nordvpn.com
au688.nordvpn.com
au689.nordvpn.com
au690.nordvpn.com
au691.nordvpn.com
au692.nordvpn.com
au693.nordvpn.com
au694.nordvpn.com
au695.nordvpn.com
au700.nordvpn.com
au701.nordvpn.com
au702.nordvpn.com
au703.nordvpn.com
au704.nordvpn.com
au705.nordvpn.com
au706.nordvpn.com
au707.nordvpn.com
au711.nordvpn.com
au712.nordvpn.com
au713.nordvpn.com
au714.nordvpn.com
au725.nordvpn.com
au726.nordvpn.com
au727.nordvpn.com
au728.nordvpn.com
au729.nordvpn.com
au730.nordvpn.com
au731.nordvpn.com
au732.nordvpn.com
au733.nordvpn.com
au734.nordvpn.com
au735.nordvpn.com
au736.nordvpn.com
au737.nordvpn.com
au738.nordvpn.com
au739.nordvpn.com
au740.nordvpn.com
au741.nordvpn.com
au742.nordvpn.com
au743.nordvpn.com
au744.nordvpn.com
au745.nordvpn.com
au746.nordvpn.com
au747.nordvpn.com
au748.nordvpn.com
au749.nordvpn.com
au750.nordvpn.com
au751.nordvpn.com
au752.nordvpn.com
au753.nordvpn.com
au754.nordvpn.com
au755.nordvpn.com
au756.nordvpn.com
au757.nordvpn.com
au758.nordvpn.com
au759.nordvpn.com
au760.nordvpn.com
au761.nordvpn.com
au762.nordvpn.com
au763.nordvpn.com
au764.nordvpn.com
au765.nordvpn.com
au766.nordvpn.com
au767.nordvpn.com
au768.nordvpn.com
au769.nordvpn.com
au770.nordvpn.com
au772.nordvpn.com
au773.nordvpn.com
au774.nordvpn.com
au775.nordvpn.com
au776.nordvpn.com
au777.nordvpn.com
au778.nordvpn.com
au779.nordvpn.com
au780.nordvpn.com
au781.nordvpn.com
au782.nordvpn.com
au783.nordvpn.com
au784.nordvpn.com
au785.nordvpn.com
au786.nordvpn.com
au787.nordvpn.com
au788.nordvpn.com
au789.nordvpn.com
au790.nordvpn.com
au791.nordvpn.com
au792.nordvpn.com
au793.nordvpn.com
au794.nordvpn.com
au795.nordvpn.com
au796.nordvpn.com
au797.nordvpn.com
au798.nordvpn.com
au799.nordvpn.com
au800.nordvpn.com
au801.nordvpn.com
au802.nordvpn.com
au803.nordvpn.com
au804.nordvpn.com
au805.nordvpn.com
au806.nordvpn.com
au807.nordvpn.com
au808.nordvpn.com
au809.nordvpn.com
au810.nordvpn.com
au811.nordvpn.com

**Comment by Zomboided** [comment]
I’m not sure why you can’t use the token approach, that seems to be a common approach used across multiple REST API implementations these days so I’m not surprised Nord are using it.If the changes don’t work for you, just download to ovpn files and use them with user defined.  It’s not a good solution though because Nord seem to change their servers a lot On 23 May 2023, at 11:33, JuliusCaeser2030 ***@***.***> wrote:﻿
That option didn't work.
The NordVPN app 5.0.0. on LibreElec 9.2.8 (Linux Kernel 4.19.127). doesn't have the option to add or use tokens. I did generate one the way you said and have one but I can't use so I reconnected back to a server here that I verified works with normal account/password. For example, in Australia; I can see there are 5 servers but in this list https://nordvpn.com/de/ovpn/ there are 50+. Only 5 configs will work. Brisbane for example is using #734, so if you download the config and change nothing during setup you can connect to au734.nordvpn.com once you download the UDP config file for this server.
e.g.
au529.nordvpn.com
au530.nordvpn.com
au531.nordvpn.com
au532.nordvpn.com
au533.nordvpn.com
au534.nordvpn.com
au535.nordvpn.com
au536.nordvpn.com
au537.nordvpn.com
au538.nordvpn.com
au569.nordvpn.com
au570.nordvpn.com
au576.nordvpn.com
au585.nordvpn.com
au586.nordvpn.com
au587.nordvpn.com
au588.nordvpn.com
au595.nordvpn.com
au596.nordvpn.com
au599.nordvpn.com
au600.nordvpn.com
au601.nordvpn.com
au602.nordvpn.com
au605.nordvpn.com
au606.nordvpn.com
au607.nordvpn.com
au610.nordvpn.com
au611.nordvpn.com
au612.nordvpn.com
au613.nordvpn.com
au614.nordvpn.com
au615.nordvpn.com
au623.nordvpn.com
au624.nordvpn.com
au638.nordvpn.com
au639.nordvpn.com
au640.nordvpn.com
au641.nordvpn.com
au642.nordvpn.com
au643.nordvpn.com
au644.nordvpn.com
au645.nordvpn.com
au646.nordvpn.com
au647.nordvpn.com
au648.nordvpn.com
au649.nordvpn.com
au650.nordvpn.com
au651.nordvpn.com
au652.nordvpn.com
au653.nordvpn.com
au654.nordvpn.com
au655.nordvpn.com
au656.nordvpn.com
au657.nordvpn.com
au658.nordvpn.com
au659.nordvpn.com
au660.nordvpn.com
au661.nordvpn.com
au662.nordvpn.com
au663.nordvpn.com
au665.nordvpn.com
au666.nordvpn.com
au667.nordvpn.com
au668.nordvpn.com
au669.nordvpn.com
au670.nordvpn.com
au671.nordvpn.com
au673.nordvpn.com
au680.nordvpn.com
au681.nordvpn.com
au682.nordvpn.com
au684.nordvpn.com
au685.nordvpn.com
au686.nordvpn.com
au688.nordvpn.com
au689.nordvpn.com
au690.nordvpn.com
au691.nordvpn.com
au692.nordvpn.com
au693.nordvpn.com
au694.nordvpn.com
au695.nordvpn.com
au700.nordvpn.com
au701.nordvpn.com
au702.nordvpn.com
au703.nordvpn.com
au704.nordvpn.com
au705.nordvpn.com
au706.nordvpn.com
au707.nordvpn.com
au711.nordvpn.com
au712.nordvpn.com
au713.nordvpn.com
au714.nordvpn.com
au725.nordvpn.com
au726.nordvpn.com
au727.nordvpn.com
au728.nordvpn.com
au729.nordvpn.com
au730.nordvpn.com
au731.nordvpn.com
au732.nordvpn.com
au733.nordvpn.com
au734.nordvpn.com
au735.nordvpn.com
au736.nordvpn.com
au737.nordvpn.com
au738.nordvpn.com
au739.nordvpn.com
au740.nordvpn.com
au741.nordvpn.com
au742.nordvpn.com
au743.nordvpn.com
au744.nordvpn.com
au745.nordvpn.com
au746.nordvpn.com
au747.nordvpn.com
au748.nordvpn.com
au749.nordvpn.com
au750.nordvpn.com
au751.nordvpn.com
au752.nordvpn.com
au753.nordvpn.com
au754.nordvpn.com
au755.nordvpn.com
au756.nordvpn.com
au757.nordvpn.com
au758.nordvpn.com
au759.nordvpn.com
au760.nordvpn.com
au761.nordvpn.com
au762.nordvpn.com
au763.nordvpn.com
au764.nordvpn.com
au765.nordvpn.com
au766.nordvpn.com
au767.nordvpn.com
au768.nordvpn.com
au769.nordvpn.com
au770.nordvpn.com
au772.nordvpn.com
au773.nordvpn.com
au774.nordvpn.com
au775.nordvpn.com
au776.nordvpn.com
au777.nordvpn.com
au778.nordvpn.com
au779.nordvpn.com
au780.nordvpn.com
au781.nordvpn.com
au782.nordvpn.com
au783.nordvpn.com
au784.nordvpn.com
au785.nordvpn.com
au786.nordvpn.com
au787.nordvpn.com
au788.nordvpn.com
au789.nordvpn.com
au790.nordvpn.com
au791.nordvpn.com
au792.nordvpn.com
au793.nordvpn.com
au794.nordvpn.com
au795.nordvpn.com
au796.nordvpn.com
au797.nordvpn.com
au798.nordvpn.com
au799.nordvpn.com
au800.nordvpn.com
au801.nordvpn.com
au802.nordvpn.com
au803.nordvpn.com
au804.nordvpn.com
au805.nordvpn.com
au806.nordvpn.com
au807.nordvpn.com
au808.nordvpn.com
au809.nordvpn.com
au810.nordvpn.com
au811.nordvpn.com
