### ISSUE TITLE
Can't connect to Express VPN

### ISSUE THREAD

**Issue by lafreak88** [Zomboided/service.vpn.manager#247]
Hallo.

I made a connection to Express VPN using the strange long user name and pasword given thru ExpressVPN. Then I choose the server (want to use Nurnberg, but tested something else to).

Cant connect. Get following log. Any idea?

Last time I installed it, it worked without problems
![2019-07-28 18_37_33-Window](https://user-images.githubusercontent.com/43384104/62010205-fd3ea600-b167-11e9-942f-6ca0b6452464.png)

**Comment by Zomboided** [comment]
That's not a log

**Comment by lafreak88** [comment]
[kodi.log](https://github.com/Zomboided/service.vpn.manager/files/3443114/kodi.log)
this one then i hope

**Comment by Zomboided** [comment]
Go here and get me an example ovpn file for Windows
https://www.expressvpn.com/support/vpn-setup/manual-config-for-windows-xp-vista-7-8-with-openvpn/#download
and then here
https://www.expressvpn.com/support/vpn-setup/manual-config-for-linux-ubuntu-with-openvpn/#download
and get me the Linux versions (they might be the same, but that's fine).

I don't understand why it's failing, but checking that I'm using the latest
config file is the place I'll start looking.  I can't get these myself
because I don't have an ExpressVPN account.

**Comment by lafreak88** [comment]
[my_expressvpn_germany_-_nuremberg_udp.ovpn.txt](https://github.com/Zomboided/service.vpn.manager/files/3448097/my_expressvpn_germany_-_nuremberg_udp.ovpn.txt)
the tut is a little bit older. there is just one file. to upload file. i added .txt, so if you delete this extension, it should be a normaek ovpn file

thx

**Comment by Zomboided** [comment]
Why only one file, are they the same for both downloads?  There are
differences against what I'm using now but I don't want to break Linux
support to fix Windows so I need to understand both.

**Comment by lafreak88** [comment]
yes, the difference between the 2 tuturials is the part with the openvpn software, but the ovpn file is the same for both. I read the whole tuturial again

**Comment by Zomboided** [comment]
Updated the ovpn.  You'll see an update in the next day or so, or you can reset the provider and delete the downloaded files and you should pick up the new ones.

If it doesn't work you'll need to ask your VPN provider why their provided file doesn't work (see the wiki page on troubleshooting too)
