### ISSUE TITLE
Kodi starts up before the openvpn connection has been established

### ISSUE THREAD

**Issue by bananenfisch** [Zomboided/service.vpn.manager#249]
As described in the Wiki "05. Monitor Options - Connect VPN before Kodi starts": i can happen, that Kodi's boot process is finished before the VPN connection has been established. As i use IPTV with PVR, which is geoblocked, the PVR requests the channel list immediately - before my VPN connection is on.

So, i fixed this for me, to extend the systemd kodi.service:

create: ~/.config/system.d/kodi.service.d/local.conf

```
[Unit]
Wants=sys-devices-virtual-net-tun0.device
After=sys-devices-virtual-net-tun0.device

```
With this, kodi.service will start as soon as the VPN is up. Well, if there is no working VPN config, then the boot process will stop here. Maybe, there could be a smarter solution for this, but sshd is still running before kodi.service, so if the connection fails for some reason, it's easy to fix.

You may consider, to add an "expert" option, to enable/disable this fix in the settings?

Anyway, for the option "Connect VPN before Kodi starts" it would be very pretty, if there would be a menu entry like "save current connection as startup config" (refresh openvpn.config). Changing server, countries, etc. is pretty easy - to change them for the next boots, you have to disable/enable the this "Connect VPN before Kodi starts" to set a new config-profile.

Thanks for your wonderful addon, which is a must have!

**Comment by Zomboided** [comment]
Hello, during boot (either before or after Kodi starts), the addon will always uses the first/default connection.  This is then the basis for some further assumptions in the code which sees the first/default connection state as the state that will be used when no connection is defined (ie when connections are all automatically changed during filtering, etc).

I think your requirement here is to change the default connection without the tedious revalidation step (or maybe boot with the last config).  But I'm confused as to why this is interesting when your goal is to avoid geolocking?  Surely you can just pick a connection that does that and use it as the default?  Why does it need to potentially change each time you boot?  If you subsequently need a different connection after boot, then can you get that through using filtering?

I think you're also asking for me to start messing wtih the config of the kodi service.  This isn't going to happen because it's not 'mine' to change.  I like that you've found an work around, but it's far from idiot proof (and idiots will just post to forums when it breaks), and I think it has the potential to get overwritten by the 'owner' of the service, or the provider of the platform (eg the awesome LibreELEC guys).  If there's something I can put in the openvpn service that the addon does 'own', then I'm happy to consider that.

**Comment by bananenfisch** [comment]
Hi, thanks for reply. To clarify, here some steps to reproduce (i use NordVPN):

First, default setting:
"Automatically connect to first VPN" ON
"Connect VPN before Kodi starts" OFF

1. kodi starts
2. VPN-connect from ~/.kodi/addons/service.vpn.manager/NordVPN/[primary-country].ovpn
3. all-right.. but maybe the VPN is slow, reconnecting to get another server
4. ~/.kodi/addons/service.vpn.manager/NordVPN/[primary-country].ovpn gets refreshed
5. reconnecting - all right
6. reboot...
7. VPN connect to the refreshed ~/.kodi/addons/service.vpn.manager/[provider]/[primary].ovpn

Then, again with "Connect VPN before Kodi starts" ON
1. VPN-connect from /storage/.config/openvpn.config
2. kodi starts
3. all-right.. but maybe the VPN is slow, reconnecting to get another server
4. ~/.kodi/addons/service.vpn.manager/NordVPN/[primary-country].ovpn gets refreshed
5. reconnecting - all right
6. reboot...
7. VPN-connect from the old /storage/.config/openvpn.config again

So, i think, the ~/.config/openvpn.config should also get refreshed as soon as the user reconnect/refresh his primary connection. Because if not, then he will always start with the old profile - the only way to change the default profile is, to disable the option and re-enable.

A fix could be to symlink ~/.config/openvpn.config to the primary config in ~/.kodi/addons/service.vpn.manager instead copying the file on setting-changes...

Because of using the different ~/.config/openvpn.config profile, the display of "Display VPN status" and "Display enhanced information" shows potentially a wrong VPN server (because it reads from the settings in ~/.kodi/addons/service.vpn.manager, while openvpn use ~/.config/openvpn.config when this option is active).

The other thing... start kodi.service, when tun0 is up... you are right... even if there could be a smarter solution, none of them would be idiot proof. So, users can config this like me on own risk...

Thanks!

**Comment by Zomboided** [comment]
Ok, now you've said Nord I understand this better.

Nord support is great because they let me use their API and on connection from within Kodi the best server for a chosen geo is picked dynamically.

However, this has the downside that any attempt to boot before Kodi will use the last best server it connected to with the hope that it still works (most of the time it should, otherwise this gets fixed after boot), and that it's a sufficiently fast server - ie the load is low at that time (who knows if this will be true).  I run my Kodi boxes constantly so the last connection could be days or weeks old.  

I think you're telling me here though is that the server is actually even older, and is the one identified during validation - I'll go look at this, I agree that if you're using the first/default connection, it could update the ovpn used during boot with the last server connected to - very reasonable request.  I still don't think this gets you what you want though, as the server could still be stale.

From within Kodi you can use the cycle button to reconnect at any time and it will pick the 'best' server again.  You don't need to revalidate a connection to do this.  I added this because the best server could change over time.  

With regards to the display info, for Nord it is dynamic _if you've connected in the Kodi environment_.  If you boot before the Kodi environment happens then I can't remember how things get resolved and whether it's dynamic or static as you've suggested (you're certainly right it's static for other providers, but these providers are static configs).  Either way, this isn't going to change as I have to 'guess' at what happened before boot and then validate it when the addon is available.

Outside of the Kodi environment, short of me writing a bunch of code to be run before Kodi boots which does some stuff with the Nord API to get the current 'best server', it will alway used the last connected server - this behaviour isn't going to change.

**Comment by bananenfisch** [comment]
Yes - i agree with all. I think, creating a symlink instead copying to openvpn.config will solve this: in platform.py - or, if this is not possible, execute "copySystemdFiles" on reconnect the default connection AND "Connect VPN before Kodi starts" is enabled.

Then, when i "cycle" to another server, it will use this on next boot also - and the display infos would be also right.

But i'm not sure, if this will break other things.

For now - for my settings, i changed the openvpn.service:
-ExecStart=/usr/sbin/openvpn --daemon --config /storage/.config/openvpn.config
+ExecStart=/usr/sbin/openvpn --daemon --config /storage/.kodi/addons/service.vpn.manager/NordVPN/[primary-country].ovpn

... and all works as excepted.

**Comment by Zomboided** [comment]
6.2.3 has been posted on Github, but isn't in the repo.  I've not been able to test it properly as I don't have a current NordVPN account.  It does appear to refresh the boot config when the first/default connection is established.  Which is what we discussed.  Please let me know if this is working for you and I'll close this and publish it on the repo.

Here's the issue though...if you never stop/start the connection after boot, it'll never get updated.  Nothing I can do about this (short of implementing the Nord API outside of Kodi, which I said I'm not doing).  So you're going to have to rely on filtering to make this happen.  If you don't want to do this, you could have a cron job which runs at a suitable time of day/night and either uses the API via Kodi to restart the connection (details on the wiki), or you could just kill openvpn and let the addon reconnect.

**Comment by bananenfisch** [comment]
Hi, i've tested it, and all looks very good:
1. enable connect before kodi starts:
1a. switch to a secondary/third/... connection: openvpn.config stays! good!
1b. switch/reconnect to first/default connection: openvpn.config gehts updated - thats what i want, good!
2. disable connect before kodi starts:
openvpn.config stays - good! after enabling connect before starts: openvpn.config gets updated!

I have tested various cycles, primary, secondary, reboots, etc. - and i see now, when the option is enabled (or get enabled), to openvpn.config gets updated.

So, i think, you can publish and close this issue. Thanks a lot for your work and quick fix!!!

Of course, if i never change/reconnect, then the profile will stay - but that's ok. Users will reconnect, if some connection lags - and with this fix now, they can reconnect and have the refreshed settings also on next reboot (when the option start vpn before kodi - others have it without this fix).

Thanks again! :-)

**Comment by bananenfisch** [comment]
Also with this fix: the display is now correct as openvpn.config is related to the latest service.vpn.manager/NordVPN file after reboot!

**Comment by Zomboided** [comment]
Excellent news!  Thanks for your input and help.  I'll put this on the repo when I get the chance.
