### ISSUE TITLE
Sometimes a different VPN connection is used than reported

### ISSUE THREAD

**Issue by peno64** [Zomboided/service.vpn.manager#265]
Sometimes I have the following issue.
I am connected to a NordVPN server.
In this simulation case be119.nordvpn.com with ip address 77.243.191.84 as seen in printscreen screenshot062.png
I have another addon which shows me the result of https://real-debrid.com/vpn to see if they don't block this ip address. You can find this addon if you need it here: https://github.com/peno64/script.RealDebrid.vpn/releases
The result is shown in printscreen screenshot063.png
As you can see the two ip addresses are equal (77.243.191.84) as expected.
Now I have assigned the function key f1 to cycle trough the predefined  vpn and I press it two times to reconnect to the same country (Belgium) to get (hopefully) a new vpn server. 
See printscreens screenshot064.png after pressing twice f1 and then screenshot065.png, screenshot066.png and screenshot067.png
So everything seems to have gone well.
I also have the function key f2 assigned to the vpn extended info from your addon and this shows now that I am connected to be80.nordvpn.com ip address 37.120.143.4
See screenshot068.png
But when I ask via the other addon to real debrid what the status is it says 77.243.191.84
see printscreen screenshot069.png
So there is a problem here because your addon tells me that I am connected to be80.nordvpn.com ip address 37.120.143.4 but actually I am still connected to the previous server!
Note that this does not happen always but sometimes.
Maybe a first step would be to show in your extended info also the effective ip address connected to. Is that possible? But of course I would also like to have this problem solved if possible.
The reason why I have to connect to another server sometimes is that real debrid is blocking some ip addresses and I must then connect to another server that they don't block.
I use the latest vpn manager version 6.3.1 but not sure it this is related to this last version. I think I had this problem with a previous version also but I didn't realise it at that moment that this was the problem.

Thank you

![screenshot069](https://user-images.githubusercontent.com/32430988/68542103-fea77d80-03a8-11ea-8716-a05e645984b3.png)
![screenshot062](https://user-images.githubusercontent.com/32430988/68542104-fea77d80-03a8-11ea-8f6b-b21d81129d11.png)
![screenshot063](https://user-images.githubusercontent.com/32430988/68542105-fea77d80-03a8-11ea-8320-7e5a464d194c.png)
![screenshot064](https://user-images.githubusercontent.com/32430988/68542106-ff401400-03a8-11ea-9318-1d17c3c40a18.png)
![screenshot065](https://user-images.githubusercontent.com/32430988/68542108-ff401400-03a8-11ea-848c-d8501237e6c7.png)
![screenshot066](https://user-images.githubusercontent.com/32430988/68542109-ff401400-03a8-11ea-883f-0e59185fcfba.png)
![screenshot067](https://user-images.githubusercontent.com/32430988/68542110-ff401400-03a8-11ea-8c56-f59f0116b839.png)
![screenshot068](https://user-images.githubusercontent.com/32430988/68542111-ff401400-03a8-11ea-8d24-b0fa19544358.png)

**Comment by Zomboided** [comment]
The effect IP address is generated by connecting to the VPN and asking a third party API what it sees.  This isn’t something that I get from directly Nord, or have any control over.  I guess Nord does because they’d determine the end point they share and it wouldn’t be a total shocker if they shared end points across all of their 1000s of servers.

The reconnect, if I recall correctly, will just go through the reconnect sequence again. There’s no guarantee that you’ll get a different server - it’s up to Nord to tell me which one is most suitable. If I can’t connect to that one then it’ll move to the next one.  The list of servers I get is based on location and load, it doesn’t have memory as to what servers you’ve connected to recently (for good reason, the conditions of the servers are changing constantly)

So if I’ve understood your problem correctly, I don’t think there’s anything to fix here. You want blacklisting of servers with some way to actively manage that list (ie to add a server that you want to avoid) based on the end point. That’s too niche a use case which only relates to one VPN provider (two at best, everything else is static) and really is too much effort to implement.  If you want to manage the list of servers that you connect to, then that’s why User Defined exists.

If I’ve not understood this correctly and you think that there’s an issue getting the effect IP after reconnect then get me a full debug log where I’ll see what’s being returned from the APIs

**Comment by peno64** [comment]
You say "The effect IP address is generated by connecting to the VPN and asking a third party API what it sees."
Strange then that this IP is different from what real debrid is seeing. See screenshots 068 and 069 where vpn manager says 37.120.143.4 and real debrid says 77.243.191.84 
If the third party api says 37.120.143.4 then why is real debrid saying 77.243.191384 ?

**Comment by Zomboided** [comment]
No clue...I'm happy to look at log to see what the API is returning.  You could probably look yourself, I think it's all traced in plain text.  If I don't get a response then it takes ages and eventually will just show unknown.  It doesn't reuse what it did previously (if the API is called)

**Comment by Zomboided** [comment]
No log, no problem, closing this.
