### ISSUE TITLE
Cannot connect to my openvpn

### ISSUE THREAD

**Issue by PrzemekSkw** [Zomboided/service.vpn.manager#269]
Hi. I have openvpn installed on my debian server and i try to connect on libreelec installed to Rpi 4B. I install Zomboided repo and then VPN Manager. Then after wizard ends I ser error with that:

    Wed Nov 27 21:25:50 2019 Insufficient 
    key material or header
     text not found in file '[[INLINE]]' 
    (0/128/256 bytes found/
    min/max)
    Wed Nov 27 21:25:50 2019 Exiting due to 
    fatal error

My openvpn script on debian server generates only one .ovpn file and that works perfect on laptops, Android smartphone and osmc with Rpi2.
Can somebody help me?
Regards,
Przemek

**Comment by Zomboided** [comment]
Go read the trouble shooting guide on the wiki.  If you want help, provide proper debug.

**Comment by PrzemekSkw** [comment]
@Zomboided Hi, thanks for fast reply. I don't know what proper debug means. I don't see my problem im Troubleshotting guide.
I generate that log on that http://ix.io/230q

**Comment by Zomboided** [comment]
Switch debug on in settings/advanced.  But there's nothing in this log suggesting VPN Mgr is crashing.  The last thing is that you're trying to play a video from some remote site, and it's crashing.  RPi 4 support seems patchy at the moment, I'd eliminate the VPN and just try and get it working without on a platform that isn't in beta.  My interest in debugging problems caused by beta builds is close to 0.
