### ISSUE TITLE
Error opening config file

### ISSUE THREAD

**Issue by wadiv76** [Zomboided/service.vpn.manager#277]
During the wizard setup, I get the following error attempting to open the configuration.  It appears that the vpn manager is expecting the configs to be at a location other than where they are.  Is there a setting I can change or update to point the service.vpn.manager to the correct path?  I am running win10 Kodi 18.5 

Options error: In [CMD-LINE]:1 Error opening configuration file:
C:\Users\[Username]\AppData\Roaming\Kodi\addons\service.vpn.manager\PIAUS West(UDP).opvn
Use --help for more information

Actual path
C:\Users\[Username]\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\addons\service.vpn.manager\PIA

**Comment by Zomboided** [comment]
This works fine for me, with that provider.  Get a full debug log after
going to the settings screen and switching on Advanced/Enable debug for
this addon

**Comment by wadiv76** [comment]
[kodi_19-12-29_17-37-49.log](https://github.com/Zomboided/service.vpn.manager/files/4008719/kodi_19-12-29_17-37-49.log)

**Comment by Zomboided** [comment]
This log shows no errors, and it appears to be creating the ovpn files it
needs.  So let's start by going to the settings, then "Utilities" tab, then
"Reset VPN" and then "Delete downloaded files" or whatever they're called.

Then restart Kodi, and start again.  You should get the wizard back.  Run
through everything as per the log, but use default encryption rather than
strong - I use default on mine so this is one difference that might be
causing the problem.

If default fails, then this is the command that's used to start the
connection :
"D:\Program Files\OpenVPN\bin\openvpn"
"C:\Users\wadiv\AppData\Roaming\Kodi\addons\service.vpn.manager\PIA\US West
(UDP).ovpn"

Can you navigate to
C:\Users\wadiv\AppData\Roaming\Kodi\addons\service.vpn.manager\PIA\" and
see if any files exist.  If "US West (UDP).ovpn" exists, then please share
it - there's no personal info in it.

If the file exists and has a bunch of parameters in it, the next thing to
do would be to then start a command line, and enter the command above.
You'd need to start the command line as an administrator.  What happens
then?

My feeling is that this is either an issue with strong encryption, or it's
a permissions issue with your machine.  This is bread and butter stuff for
this addon and I haven't seen a failure like this before.

**Comment by gahujipo** [comment]
I had the exact same behaviour yesterday on Windows 10 in the last version of Kodi from Windows App Store. I even tried to create the destination directory by hand, but the .ovpn-file didn't appear after clicking through the wizard. I tried it with the service "VPN Unlimited".

**Comment by Zomboided** [comment]
Are you using Kodi users?

**Comment by gahujipo** [comment]
Do you mean profiles? No, I don't use them.

**Comment by wadiv76** [comment]
After running through the steps you provided, I can confirm it does not connect with the same error and there are no files/folders in C:\Users\wadiv\AppData\Roaming\Kodi\addons

The downloaded .ovpn files are all in C:\Users\wadiv\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalCache\Roaming\Kodi\addons\service.vpn.manager\PIA
Which is where the Kodi Windows 10 Application lives

**Comment by Zomboided** [comment]
The paths are resolved by a kodi call, I don’t know why it’s not working here. I’ll read the documentation somewhen to see if it copes with this now.  Meantime you can download it directly rather than use the store which will  allow it to resolve paths properly

**Comment by Zomboided** [comment]
https://forum.kodi.tv/showthread.php?tid=339891

This is a Kodi issue.  Don't use Windows store for the install, or wait for Kodi to fix the way their paths are resolved.  I guess I could fix this by adding more complexity and letting the user specify where the variety of directories are, but I don't want to do that to work around a Kodi issue.
