### ISSUE TITLE
Only use VPN for accessing resources

### ISSUE THREAD

**Issue by greendeath** [Zomboided/service.vpn.manager#285]
Hello,
I would like to use the OpenVPN service only for accessing resources on the other side of the tunnel. Therefore, I don't want the whole traffic going through the VPN.

If this is no need for others. I would ask you, where do you set routes? (In the log I can see the `ip route add 0.0.0.0/1 ...`)

Thanks for your help
Cheers

**Comment by Zomboided** [comment]
This isn't a typical use case because most people aren't connecting to their own VPN (which I guess you are).  I can't help with how you'd set up openvpn to push these settings on connection, or how you'd do it in the up and down scripts, but these are you options to making this work.  up and down script usage is documented in the wiki
