### ISSUE TITLE
Connect to foreign country ok, but still IP from my provider

### ISSUE THREAD

**Issue by lafreak88** [Zomboided/service.vpn.manager#290]
Hello

Not the best title, I know. Had no idea for a better one

Tested with express and Nord VPN.

I connect to a server in a foreign country, I get a message the connecting to it was successfully.
When I test it with a "what's my IP" website, I am still connected with with m official provider

Tested express VPN with openvpn program on windows 10. Here I don't have this problem, website are showing ip from the foreign country.

I hope you understand what I mean.

Do you have an idea?

Thanks in advance
Christoph

**Comment by Zomboided** [comment]
The addon uses an equivalent service to determine the country and remote IP address.  This won't be tried unless it thinks the connection has worked.  You can look in the log and see the trace of this (with all the trace options turned on).  If this is showing a differnet location and IP to your regular one (which can be wrong as those services are not all that accurate), then I'd assume the VPN was good.

If you're seeing something else, via a browser then you should go understand whether the browser is using the same route.  You can google to work out how to look at the IP tables.  You should also check that the VPN is still running - it gets killed when Kodi exits.

**Comment by lafreak88** [comment]
![IMG_20200521_215242](https://user-images.githubusercontent.com/43384104/82600840-d6e26f00-9bae-11ea-8074-4f450e43fb04.jpg)

![IMG_20200521_215202](https://user-images.githubusercontent.com/43384104/82600786-c0d4ae80-9bae-11ea-841c-d376e22b7bc6.jpg)

![IMG_20200521_215705](https://user-images.githubusercontent.com/43384104/82600863-e1046d80-9bae-11ea-8b9d-05c586458058.jpg)

Hello

Not Sure if I understood everything good.

Attached some pictures. The IP the website shows is the same, doesn't matter if I use VPN in Kodi or not. It's the same the message shows when I connect to VPN. 

Perhaps we can figure it out with this pictures?

**Comment by Zomboided** [comment]
I'm not sure what you're doing.

You need to ensure you're not using a VPN elsewhere on the system - this includes running any VPN provider software which may conflict with the addon wanting to manage the connection.

You need to run Kodi in admin mode.  I'm suspicious you're not because it looks like you're connecting but openvpn is failing to add routes to the routing table which would enable the flow of traffic through the VPN

**Comment by lafreak88** [comment]
In the pictures showed in my post I don't use any other VPN. Just that one in Kodi (your plugin)

I never Started KODi as admin in the past. But it was the solution now :)

Thanks for the tip

**Comment by raulcano** [comment]
Hi, I'm having a similar problem.
It says that the initial connection is OK (to a different country), but then it shows the server from the city I'm in with my regular IP.
After a few seconds it disconnects and when I reconnect , the same occurs.
I changed the VPN manager to connect before Kodi starts, with same result.
Any ideas? thanks in advance!

I'm running LibreElec 9.0.2
Kodi Leia 18.2

Here a kodi log:
https://pastebin.com/DRjiPE8y

OpenVPN log:
I cannot find a file with the openvpn log - I've search google for that but I don't know how to paste it here in text format, so I took a pic from the log
![image](https://user-images.githubusercontent.com/1665639/82760939-e3d8ab80-9dc4-11ea-944d-32946dae42c9.png)

**Comment by Zomboided** [comment]
lafreak88's problem is fixed so this is getting closed.
raulcano, your problem is that you're using Cyberghost and they've taken to updating the provider files themselves so you can go talk to their support team to determine why they can't get this right when 40 other providers have no problems, I'm not gonna help here.   You should check you have the latest files before doing this though....if you connect and the icon is green, you're good, if you connect and it's blue, then you need to go through and validate the connections again.

**Comment by raulcano** [comment]
Ok, the icon gets green, but it disconnects after that. I'll talk to them then and see what happens.
thanks for the answer anyway.
cheers.
