### ISSUE TITLE
Multiple VPN providers

### ISSUE THREAD

**Issue by jonk999** [Zomboided/service.vpn.manager#294]
Is it possible to use with multiple VPN providers?
Eg: setup for Windscribe and PIA

Not sure if I missed something somewhere on if and how it can be done.

**Comment by Zomboided** [comment]
You need to get the ovpn files for the locations you want to use from each provider along with any supporting keys and certs and use user defined.  The wizard might help otherwise there’s a bunch of documentation on the wiki.  You’ll need to resolve the password files manually because the IDs will clash.

This isn’t a common or interesting use case so I’m not planning on building in any native support
