### ISSUE TITLE
NordVPN not working with default VPN providers list

### ISSUE THREAD

**Issue by mflorezm** [Zomboided/service.vpn.manager#302]
Hi, I'm using 6.3.5 on libreelec 9.2.5 (RPi4) Leia 18.8, and i can not connect to NordVPN using the default VPN providers list. Not matter if trying with the emaill and password (Nord account like on Andrid app) or the credentials (that are inside the dashboard of NordVPN).

The only way that it works is using a User Defined profile and uploading the ovpn file; it works using the credentials (that are inside the dashboard of NordVPN).

The problem this way is that the VPN is always with the same server (ovpn file) instead of chossing the best server as i understand that is the way it should works.

I have a DNS leaking problem too, and tried the up.sh and down.sh from GewoonGijs, but the service.vpn.manager (don't use or don't find the scripts) even as the option is enabled on settings and the files are on /storage/.kodi/userdata/addon_data/service.vpn.manager/ same folder as the ovpn uploaded profiles.

Any ideas? All help will be granted. Thanks.

MFM

**Comment by Zomboided** [comment]
I cant' guess why you can't connect and you're not sharing a log, but I've just pushed out 6.3.6 which increases the timeout for Nord...maybe there are cases where their authentication is slow.  You should try this, otherwise look at the trouble shooting page on the wiki to determine how to get a log with the right tracing.

With regards to the up/down scripts, the instructions for using these are also on the wiki.  What you put in these scripts and how you use them is your deal, I don't want to get into debugging differences in Linux installs for things that are not related to my addon and there's already much documentation out there on this issue.  You can verify that the up/down scripts have been enabled by looking in the /storage/.kodi/addons/service.vpn.manager/nordvpn and viewing one of the .ovpn files.

**Comment by Zomboided** [comment]
Just to add, reopen if you still can't connect, with a log.
