### ISSUE TITLE
"Connected, checking location info" issue

### ISSUE THREAD

**Issue by FullonXbian** [Zomboided/service.vpn.manager#304]
Hello.

I'm having trouble properly connecting at the last step when manager checks for location info.

I'm running the latest Xbian on 18.8. I will add I have no issues when I run this on a Libreelec machine, but for a very annoying reason, I'd prefer to use Xbian.

I've tried setting up by selecting the service provider, as well as userdefined using the .ovpn files directly from the provider. Tried the DNS fix, and I've kept the up/down settings as default.

The options you provided in Issue #129 might resolve it, but coding or going into .txt is very new to me.

I can post the log, but it contains IP address info which I know you don't want. Any suggestions would be appreciated.

**Comment by Zomboided** [comment]
Issue 129 pretty much describes it.  If it connects, then the job of openvpn (and therefore VPN Mgr) is done.  If it can't reach an external site after connection, then it's almost certainly a DNS issue (and a Kodi log won't tell either of us anything interesting)

There's also this option https://github.com/Zomboided/service.vpn.manager/wiki/07.-Advanced-Options#potential-dns-fix-linux-only which may help, depending on what services your OS provides.  Otherwise it's time to start reading/learning.

**Comment by FullonXbian** [comment]
Understood. 
Thanks for the assistance!
