### ISSUE TITLE
Vpn Manager continually stops and restarts when streaming

### ISSUE THREAD

**Issue by dredgerman** [Zomboided/service.vpn.manager#31]
[kodi.txt](https://github.com/Zomboided/service.vpn.manager/files/692025/kodi.txt)
[kodiold.txt](https://github.com/Zomboided/service.vpn.manager/files/692026/kodiold.txt)
[openvpnlog.txt](https://github.com/Zomboided/service.vpn.manager/files/692027/openvpnlog.txt)

Hi,

I have an issue with VPN manager,

I have it installed on LibreElec and it works fine for normal use,

However whenever I start using an app such as Specto it cuts out repeatedly,

This is with both IPVanish and PureVPN, it never cuts out on any other service,

I get this on all streaming apps and it will not stay online no matter what I try,

Have checked everything over and over and it just wont work for some reason,

Ports for OpenVPn are forwarded etc please advise,

Thank you

**Comment by Zomboided** [comment]
The logs aren't showing any disconnections because of the addon.  It shows a bunch of times that it's detecting the openvpn task has stopped and therefore disconnected.  As a result will reconnect.  Because you're seeing it on 2 different providers, I'd also guess that it's not an issue with one of them as a result of changes they'd made.

I think that something else is coming along and killing the openvpn task.  It might be another addon, or you've got an existing systemd restart thing going on.  You can prove this by uninstalling the addon, running openvpn as a background task from the command line, (thus eliminating the addon) and then using the service.  If it disconnects when you run a particular service, then that's the answer.  If it doesn't and you can demonstrates this only happens with my addon then reinstall it, go to settings/debug, switch on debug and get me the same set of logs are you've provided again.

**Comment by dredgerman** [comment]
Hi Thank you very much,
I will investigate, unfortunately I work away and won't be back for 6 weeks, 
That sounds plausible as app seems to load up no problem,
Will do that and see what happens,
failing that will have to migrate to DDWRT router, 
Thanks very much,

**Comment by Zomboided** [comment]
Oh, I'm sorry you're on Talk Talk, but I'm glad you've found your problem.  Thanks for sharing in case other users find it useful.
