### ISSUE TITLE
Killall kills all openvpn connections 

### ISSUE THREAD

**Issue by Zuikkis** [Zomboided/service.vpn.manager#321]
Well, this is fairly obvious when using killall. :)

I have several openvpn's running. This plugin kills ALL openvpn's, even those not started by the plugin. This makes it unusable for me.. :(

So, instead of killall, can't you just find the correct pid and use "kill"?

**Comment by Zomboided** [comment]
How would you suggest I find which is the correct one?

**Comment by Zuikkis** [comment]
Oh! You have several options. 

Simplest would be using "pkill -f", but it's not available in all systems. But if it's configurable alternative to killall it shouldn't matter.

"pkill -f" is like killall but matches the entire argument string used to launch the program. 

Perhaps a cleaner solution would be to start openvpn as as a subprocess, then you could terminate it without using any external commands:

```
myvpn = subprocess.Popen("openvpn ...")
myvpn.terminate()  # SIGTERM
myvpn.kill()       # SIGKILL

```

However, at I have to admit that I just realized I can configure the plugin to not use sudo. Then it can't kill openvpn's belonging to another user. I haven't yet tried if this works, though.

**Comment by Zomboided** [comment]
The main use case of the addon is set top boxes type set ups like
LibreELEC, where a few people also need to start openvpn (via systemd)
before Kodi starts.  Subprocess approach wouldn't work here so I'd need a
bunch of logic to deal with the existing approach and the proposed new
approach.

The pkill approach I don't hate because it's largely how stuff works
today.  The logic bifurcation would be around the process kill code which
is containable.  However, there's also a bunch of logic which checks to see
if the process is still running.  I guess that would need to use pgreg or
some switch on pidof to check for arguments too.

Honestly tho, this is a pretty niche use case (ie only you've asked for it
in 5 years) and most of my users are not even capable of taking advantage
of this.  So I'd be happy to think about this if you're willing to test it
(I don't have a Linux dev environment) but I'd be happier if you found a
way of working around this (e.g. explore not using sudo for Kodi)

**Comment by peno64** [comment]
@Zuikkis 
Can't you turn around the system and link the openvpn binary to an own name and use that for your processes that should  not  be killed by  vpnmanager?

**Comment by Zuikkis** [comment]
> @Zuikkis
> Can't you turn around the system and link the openvpn binary to an own name and use that for your processes that should not be killed by vpnmanager?

Hey that's a very good idea and will work. A soft link will work. I think I'll go that route.

I'll close this issue, this is good enough solution for me. :) Thanks for the help.

**Comment by Zomboided** [comment]
Brilliant solution, thanks peno64!
