### ISSUE TITLE
FritzBox VPN?

### ISSUE THREAD

**Issue by capsload2** [Zomboided/service.vpn.manager#337]
Is it possible to add Fritzbox VPN like vpnc ?

http://www.kuemmel.wtf/?p=363

**Comment by Zomboided** [comment]
Use user defined, i'm not supporting any more providers

**Comment by capsload2** [comment]
Huh, user defined?

**Comment by peno64** [comment]
@capsload2 
https://github.com/Zomboided/service.vpn.manager/wiki/09.-User-Defined-VPNs

@Zomboided 
Maybe it would also be good to pin an issue on top where in the title it says that new providers will not be implemented and that user defined must be used since 80% of the questions are to add a new vpn service

**Comment by Zomboided** [comment]
@peno64 yup, this was the one that caused me to do just that already
