### ISSUE TITLE
Question 2 PVR Client ... 

### ISSUE THREAD

**Issue by ThoGru80** [Zomboided/service.vpn.manager#339]
Hello, 

i have 1 Question .. 

I live outside from Germany and i ised with this Addon my German TV with one PVR Client ... 

As second i install the pvr simple iptv client .. 

Is this posible if i used channel from the iptv simple client the vpn manager disconnected the vpn .... 

i know i can used same windows id as example for WINDOW_DIALOG_PVR_GROUP_MANAGER .. but then i think he diaconnected for all the vpn connection.

maybe some people can help me 

Thanks

**Comment by Zomboided** [comment]
It's been soooo long since I used this function but I think you can filter
on streams if the URL is consistent and unique.  It says something about it
in the advanced page in the wiki maybe.
Alternatively the only other way I found to do this was to insert the API
into a PVR client and allow VPN states to be associated with channels.
That project died tho as the owner wasn't really interested in expanding
the functionality and I didn't use it myself.  If you can code, you can add
some hooks into the client and call the VPN Mgr API to turn it on/off.

**Comment by ThoGru80** [comment]
OK :) i check this
