### ISSUE TITLE
Endless Connect Disconnect Reconnect loop 6.9.3

### ISSUE THREAD

**Issue by 3gem** [Zomboided/service.vpn.manager#348]
Using 6.9.3 with Kodi 19 on xbain.  Setup works fine.  ExpressVPN will initially connect, but then falls into a loop disconnecting and reconnecting.  I temporarily solved the issue by disabling "Reconnect if connection unexpectedly lost" under the "Monitor" tab.  Once that is unchecked the connection remains consistent and tun0 stays up. If i re-enable it after the connection is up it drops back into the loop.

**Comment by Zomboided** [comment]
Need a debug log as per the wiki trouble shooting page. Don’t share a full kodi debug log

**Comment by Wahwahboy** [comment]
I've come across this as I've got a similar issue - constant disconnect using the add-on with PIA (which by default, results in the reconnect attempt).
XBian OS on RPi3, service.vpn.manager=v7.0.0, killall=v23.4

The openvpn log has a few issues:
2021-12-26 22:09:28 /etc/openvpn/update-resolv-conf tun0 1500 1553 10.5.110.91 255.255.255.0 init
**2021-12-26 22:09:28 WARNING: OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0**
2021-12-26 22:09:28 add_route_ipv6(2000::/3 -> :: metric -1) dev tun0
**2021-12-26 22:09:28 sitnl_send: rtnl: generic error (-95): Operation not supported**
**2021-12-26 22:09:28 ERROR: Linux IPv6 route can't be added**
2021-12-26 22:09:28 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent
2021-12-26 22:09:28 Initialization Sequence Completed

Not sure if IPv6 is actually the issue here, I disabled IPv6 using the following in /etc/sysctl.conf
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1
net.ipv6.conf.eth0.disable_ipv6 = 1

There are no IPV6 addresses allocated and I've also disabled it in my router
>ip addr:
eth0: 
    inet 192.168.1.181/24 brd 192.168.1.255 scope global eth0
tun0:
    inet 10.15.110.79/24 scope global tun0


Same issue seen running from command line:

**Comment by Zomboided** [comment]
See the comment above...you're assuming this is an IPV6 issue.  From what little you've shared, I see a connection that completes.  I don't see any of the issues you've described.

**Comment by Wahwahboy** [comment]
Thanks for the comment. 
What I see is the AddOn's UI pop-up constantly changing between connected/disconnected so this debug log is repeated constantly.

IPV6 may not be an issue but I do know is that my provider BT in the UK have IPV6 addressing but DNS is only IPV4.
However, PIA runs perfectly well from the linux app.

I read here that trying to disable IPV6 leads to other issues.
[https://0xacab.org/leap/bitmask-vpn/-/issues/457](url)

I'll re-enable back to default try some further debugging when I get a chance and report back.

**Comment by Zomboided** [comment]
Closing this, recreate on the latest build and provide a log if this really is still a problem.
