### ISSUE TITLE
platform not detected correctly

### ISSUE THREAD

**Issue by alnixon** [Zomboided/service.vpn.manager#35]
I am running openelec on a matricom mx-2
I am using a custom build that is based on https://github.com/codesnake/OpenELEC.tv

I was facing a problem whereby the VPN Manager was trying to run /usr/sbin/openvpn but I only have it as an addon within network.openvpn/bin/openvpn

I have been able to workaround this problem with a tweak to libs/platform.py but am unsure of additional implications.  Should it be that `getPlatform()` should only check for `getAddonPath(True, "").startswith("/storage/.kodi/")` and the check for `build_number == 15` can be discarded?

**Comment by Zomboided** [comment]
build 15 of Kodi is "really old" and that check was added because for some reason OE decided to remove openvpn (which was then reintroduced in build 16).  There are some more behaviours that are keyed off of what platform it thinks it's running on, and if it's a flavour of Linux, some further behaviours that are keyed off of directory name structure.

If you want to change this, good luck.  It might work, but it might break something else.  I don't want to support random builds for this very reason though so you're on your own (plus I run Windows and LE and I'm not gonna waste time trying out other builds)

**Comment by alnixon** [comment]
Thanks for the comment, and the great plugin.
The change I've actually made was in `getOpenVPNPath()` just to return `openvpn`.  This appears to be working fine for me so far.

**Comment by alnixon** [comment]
As a suggestion, could the location of the openvpn binary be a configurable item that defaults to "platform detected" but allows a user to specify if this isn't working for them?

**Comment by Zomboided** [comment]
I've added an option to use an unqualified path call, as you've done.  It'll be in the next version, hidden in the settings/debug tab but I don't really have a way of testing it so it may or may not work....

**Comment by alnixon** [comment]
I've had chance to try out the latest version and this is working perfectly for me.  Thank you for taking the time to address this "random build" issue in a generic way that may benefit others!
