### ISSUE TITLE
Addon Issue under CoreELEC and not Windows

### ISSUE THREAD

**Issue by feerlessleadr** [Zomboided/service.vpn.manager#350]
Hi - Let me start out by saying I am not sure if this is actually an issue with the VPN Manager addon, VPN service, or potentially Kodi/CoreELEC/NHL.tv Addon, so feel free to close this straight away if I'm way off base here. 

I use a VPN to be able to watch NHL.tv, and I’m having an issue with my N2 that is not present on my test Windows machine. 

I am using VPN Manager on both machines to manage my VPN connection to NordVPN, and am able to connect fine on both machines. The issue arises when I am connected to the VPN and try to navigate to the NHL.tv game listings in the NHL.tv addon for kodi.

On my windows machine, I can navigate to the games listings and play a game without any issue while the VPN is on. However, on my N2, with the VPN on, the NHL.tv addon throws an error when trying to access the game listings, and will not let me go any farther. When the VPN is off, I can navigate to the game listing without issue (although I can’t play anything since the VPN isn’t on).

Here is a log of the error on my N2:

https://paste.ubuntu.com/p/sdjrJg9JvH/

Here is a log of the same action (and the game playing successfully) on my Windows machine:

https://paste.ubuntu.com/p/dZVpt44tdK/

Any insight would be greatly appreciated. 

Thanks

**Comment by peno64** [comment]
I totally  agree with this. I also use NordVPN and in the past  I also had chosen server that were blocked and others not. I had to disconnect and connect to make my streams work. I even made a small modification to the addon that I can read servers from a file that must be ignored because they were blocked. In that case I skip that server and let it  choose another one until it finds one that is not in my list. But this change is so specific that  it  is difficult to put this in the standard addon.

**Comment by feerlessleadr** [comment]
Thanks to both of you for your responses. Is there anyway that I can force the addon to connect to the same Nord server to test?

**Comment by Zomboided** [comment]
Copy an ovpn file from /kodi/addons/service.vpn.manager/Nord  directory and connect using the command line. You can see the command used in the log.  Disable the addon before using the command line tho otherwise there will be conflicts.

Or you can download the “right” server ovpn file from Nord with the certs, etc and feed that into user defined
