### ISSUE TITLE
Update PrivateVPN server list

### ISSUE THREAD

**Issue by chadbitmachine** [Zomboided/service.vpn.manager#362]
hi guys, can we update the server list for PrivateVPN?

You can find the updated locations and server addresses on this page: https://privatevpn.com/serverlist/

many thanks!

**Comment by Zomboided** [comment]
Hello, the locations are generated from the ovpn files provided by the VPN
provider.  In the case of PrivateVPN, these would be available to download
on this page (step 4)
https://privatevpn.com/support/getting-started/routers/asus-rt-models/openvpn

PrivateVPN would appear to be supplying files that are up to 3 years out of
date.  I'd be happy for you to request their support to update these
files.  Must be a ball ache for someone who wants to use their service with
a router rather than their software.

I would not be happy to use the link you've provided to enter all of the
new addresses into the right format and instead would just deprecate
PrivateVPN support and suggest you use User Defined with the profiles you
want to upload.

**Comment by Zomboided** [comment]
Deprecated PrivateVPN.  Can reverse this is someone is willing to provide udpated opvn files.
