### ISSUE TITLE
VPN automation with aggregation addons 

### ISSUE THREAD

**Issue by siliconhippy** [Zomboided/service.vpn.manager#387]
Hi again,

Re: https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

There are Kodi aggregation addons like above that extract the playlist and epg from video addons like Plex Live and output to PVR IPTV Simple.

Question: How would I use Zomboided with such an arrangement?

1. If I do the IPTV Merge extraction and click a Plex Live channel in Live TV, having put Plex Live addon on a VPN via Zomboided, will this automatically switch on the specific VPN/VPN location for that particular channel?

What should the switching time be, as a rough estimate?

2. Alternatively, if above cannot work, is it possible to assign a VPN via Zomboided to a particular playlist.m3u, either remote or in a local Kodi directory ?

**Comment by Zomboided** [comment]
I did something like this in a IPTV addon some years ago but it wasn't a
great experience.  The VPN switching time was about 10 seconds, but could
be longer if the connection didn't take immediately. I had to modify the
IPTV addon to call an API I put into my addon to do the switching, but I
can't remember how I determined which channel to switch.  I guess there was
some whitelist or blacklist type mechanism.  It worked, but it wasn't a
great experience and I didn't pursue this as a way of automating connection
switching.

I've also looked at switching based on selected media.  There's a callback
that happens when media is started, but the media won't start if it's geo
locked and you need the connection to be made first....so this is a
non-starter.  Really the only way to do this is to be part of the addon
that lets you select the playlist and switch the connection before the
media starts, and if you're going directly from Kodi to do this rather than
through an addon, I really can't think how you'd intercept this to do the
switch.

**Comment by siliconhippy** [comment]
Ok thanks ....was afraid of this being a problem ☺️

How about #2?

**Comment by Zomboided** [comment]
That’s the point I’m making about playback. When you trigger a playlist it just causes some playback to happen. I’m not sure if the callback reports it’s playing because of a playlist it doesn’t matter because the addon won’t be told unless playback starts successfully On 11 Feb 2023, at 18:51, siliconhippy ***@***.***> wrote:﻿
Ok thanks ....was afraid of this being a problem ☺️
How about #2?
