### ISSUE TITLE
Issue with connecting Vypr VPN LibreElec v10.4

### ISSUE THREAD

**Issue by craig846** [Zomboided/service.vpn.manager#398]
Since the update 2 days ago, I cannot connect to Vypr VPN anymore. When I go to validate the first VPN connection, a dialogue box comes up with 3 options: Vypr Strong Encryption, Giganew account and Vypr default encryption. No matter which option I select it comes up with another dialogue box saying error updating .ovpn files or creating user credentials file. I have check my usr credentials are fine.
I am running Libre Elec V10.4 and it is a clean load. This error only started 2 days ago since a blue prompt came up to update opvn files.
Can you help?

**Comment by peno64** [comment]
Doesnt sound related to the last charges. I suggest that you try-out version 7.0.0 to see if you also have the problem and even go back further


________________________________
From: craig846 ***@***.***>
Sent: Saturday, April 8, 2023 1:36:21 AM
To: Zomboided/service.vpn.manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Zomboided/service.vpn.manager] Issue with connecting Vypr VPN LibreElec v10.4 (Issue #398)


Since the update 2 days ago, I cannot connect to Vypr VPN anymore. When I go to validate the first VPN connection, a dialogue box comes up with 3 options: Vypr Strong Encryption, Giganew account and Vypr default encryption. No matter which option I select it comes up with another dialogue box saying error updating .ovpn files or creating user credentials file. I have check my usr credentials are fine.
I am running Libre Elec V10.4 and it is a clean load. This error only started 2 days ago since a blue prompt came up to update opvn files.
Can you help?

**Comment by Zomboided** [comment]
Pushed a bad update out, you should see another prompt to update.  If not, go to setting/utilities and Remove all downloaded VPN provider files to try again.
