### ISSUE TITLE
Userdefined vpn

### ISSUE THREAD

**Issue by estimadarocha** [Zomboided/service.vpn.manager#6]
Hi, 

i am trying to put a userdefined vpn to work... i have read manuals but have no sucess.

attached are the files of my vpn.

This vpn have no need of username and password just the keys and certs.

Thanks

[wepi.zip](https://github.com/Zomboided/service.vpn.manager/files/567841/wepi.zip)

**Comment by Zomboided** [comment]
Guessing at what your problem is without seeing a log, this bit of the readme is relevant : 

Each .ovpn file can include the tag, '#PATH' which will be replaced with the working directory path. This can be used to point at any password, key or cert files which will be copied across from the userdata directory. An example to how you might use this is 'auth-user-pass #PATH/pass.txt'

You probably need to do this for each of the files you're referencing in the .ovpn

**Comment by estimadarocha** [comment]
@Zomboided i did make that changes

original ovpn lines:

ca ca.crt
dh dh2048.pem
cert wepi.crt
key wepi.key

changed ovpn lines:

ca #PATH/ca.crt
dh #PATH/dh2048.pem
cert #PATH/wepi.crt
key #PATH/wepi.key

all those files i put in \Userdata\addon_data\service.vpn.manager\UserDefined

**Comment by estimadarocha** [comment]
log says:
user.crt  ----> no such file or directory
user.key  ----> no such file or directory

**Comment by estimadarocha** [comment]
@Zomboided also tried:
´
ca #PATH/storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/ca.crt
dh #PATH/storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/dh2048.pem
cert #PATH/storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/wepi.crt
key #PATH/storage/.kodi/userdata/addon_data/service.vpn.manager/UserDefined/wepi.key

**Comment by estimadarocha** [comment]
i installed version 2.1.1 and now when i go to vpn connections and click to choose first vpn connection it quits to initial information addon page, with other version it asks for ovpn that i had put on /service.vpn.manager/UserDefined/

**Comment by Zomboided** [comment]
ca #PATH/ca.crt
dh #PATH/dh2048.pem
cert #PATH/wepi.crt
key #PATH/wepi.key

This is right, your second example is not.  You need to go to settings/utilities/reset .ovpn files after making the change otherwise it won't be picked up.
