### ISSUE TITLE
Connecting problem

### ISSUE THREAD

**Issue by pierozek89** [Zomboided/service.vpn.manager#78]
Hi there!

I'm having problem with launching VPN Manager on my Rp3 with OSMC

I'm using AzireVPN as a VPN provider (not listed in VPN manager so I'm trying to connect with Defined User)

Manager was able to found auth-user-pass, key, cert and askpass tags but there is an information "Found key and cert tags all with the same filename, but no key or certificate filer were supplied" and that's strange because I have all the files in one place and they were coppied into /UserDefined/

I tried like a milion ways to connect, using I think all the options in the settings but in the end I always have this error 

" Options error:--keepalive conflicts with --ping, --ping-exit, or -ping.restart. If you use -keepalive, you don't need any of the other --ping directives"

Honestly I don't know that that means - I'm pretty lame in coding/programming etc

Other addon OpenVPN works fine, but I'd like to switch to VPN Manager

**Comment by Zomboided** [comment]
Its up to you to fix this, I don't know anything about thisprovider. The ping problem can probably be fixed by going to settings/debug and finding the ping option. Reset the vpn provider files after you do this. The first error might get fixed when you try and connect. If not you'll need to edit the files you supply. See the wiki
