### ISSUE TITLE
LZ4 Compression support

### ISSUE THREAD

**Issue by cmstew** [Zomboided/service.vpn.manager#82]
Hey there,

I was wondering if it was possible to incorporate LZ4 Compression into VPN Manager. I run my own VPN server and I had to use the older lzo compression to get my kodi, running on a Raspberry Pi 3, to connect. 

I'm aware that this compression method is only available with OpenVPN v2.4+. So perhaps that's the problem in and of itself. I don't fully understand how VPN Manager uses OpenVPN so I suppose this could be an issue with the version of OpenVPN that's installed on my raspberry pi rather than your plugin.

**Comment by Zomboided** [comment]
VPN Mgr just calls openvpn with an ovpn file. If your base OS has an up to date version of openvpn and you're using the User Defined setting, supplying your own ovpn files then there's nothing within VPN Mgr that will prevent you doing this.

As an aside I think the newer versions of LibreELEC use newer versions of openvpn, otherwise look at some of the leading edge beta builds (which may not be ideal for other reasons...)

**Comment by cmstew** [comment]
Ahh, you are correct. That makes sense. I wasn't sure if you were tying into the systems openvpn or if you were accessing your own somehow.

My raspberry pi only has version 2.3.4 which would by why it isn't working. I should be able to just build the newer version from source and install it that way.

Thanks for the tip. :)
