### ISSUE TITLE
Hangs while checking location info after connection

### ISSUE THREAD

**Issue by sevketcaba** [Zomboided/service.vpn.manager#84]
While establishing the first time connection, The system waits at the message 'Connecting the first VPN. Connected, checking location info' and Cancel button does not work either. 

Test System: Raspberry Pi 3, OpenELEC v8.0.4, VyperVPN

**Comment by Zomboided** [comment]
I just checked the VyprVPN files and they've not changed since end of 2016 so there's not a problem with the provider.  You'll need to trouble shoot your environment, maybe try the latest LibreELEC build 
https://github.com/Zomboided/service.vpn.manager/wiki/13.-Trouble-Shooting#debugging-vpn-problems
